### ISSUE TITLE
Cygwin suppport?

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#100]
Last Sunday, I updated my computer to Windows 10, and now I'm trying to get some various stuff working. BUT...I hate all the text editors I can find. I don't like Vim, Emacs is really awful, Notepad doesn't work with LF line endings, Notepad++ crashes, and the only things that work are Atom (slow as heck and also crashes) and VS Code (better, but limited autocomplete; at least it doesn't crash). It'd be *awesome* if I could get Howl working under Cygwin so that I have a text editor I actually *like* running.

HOWEVER...I don't really want to spend too much time working on it if it's not going to be supported. Which brings me to the question: what would be the position on Cygwin being a supported platform?

**Comment by nilnor** [comment]
I'm open for supporting it as a platform - it would be a nice to offer a Windows version, provided that someone can maintain it.  Since Howl builds a lot on top the g* lib family, it should at least theoretically have a high chance of working on Windows without major changes. Not to say that there would be work involved of course, I have tried to keep unixisms out of the code along the way,  but I'm bound to have failed.

**Comment by kirbyfan64** [comment]
Status update: It *almost* works.

Basically, LuaJIT won't build with Cygwin 64-bit. I needed to download the luajit package via the Cygwin installer and comment out the lines in Howl that build it. In order to run it, you need to do:

```
startx $PWD/howl
```

Now I'm getting:

```
** (howl:21068): CRITICAL **: Failed to run script: /home/Ryan/howl/lib/howl/init.lua:155: /home/Ryan/howl/lib/ext/moonscript/moonscript/base.lua:65: /home/Ryan/howl/lib/howl/ustring.moon: not enough memory
```

which is weird, because there's *plenty* of memory. Huh...

Worst part: right now I'm stuck using Atom to edit the files, and I can literally feel the lag. It's horrible. :)

**Comment by nilnor** [comment]
Ah, you're trying to run it like so. There's not much I can say about that, except it sounds like a LuaJIT build thing with memory in the low range not being available. As per the LuaJIT page, cygwin is only supported for 32-bit builds, for 64-bit MSVC + SDK or the windsdk is needed. Anyway, what would be ideal for a Windows build is to have a "native" build, i.e. with Gtk built for Windows and not relying on any X server (see for example http://www.gtk.org/download/windows.php). That's probably a lot more work than getting it up and running under a cygwin x server, but would make for a better result as it would make it more of a "real" Windows application. I didn't realize you aimed to run it under the cygwin x server, that's great if it works but in the long run a "native" build would really be ideal.

**Comment by kirbyfan64** [comment]
@nilnor Well, this was supposed to be a "temporary solution" so that I could have a semi-working Howl to edit stuff with until I got it working natively. Darn. :/

**Comment by shalabhc** [comment]
@kirbyfan64 - kudos for attempting a Windows build! For a temporary solution, how about running Linux in a VM within Windows and using sshfs or samba to mount your Windows drive in Linux? Crazy, yes, but should be easier to get that to work than a Windows build.

Also I agree that a proper native build would use the native GTK and Microsoft's compiler.

**Comment by nilnor** [comment]
Closing this as what we really want is a native Windows build, and Windows support is at any rate something someone (i.e. not me) would have to do and support, at which point a PR would be the way forward.
