### ISSUE TITLE
Freeze saving large files

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#105]
Basically, open a REALLY huge file in Howl (I did [Index.h](https://github.com/llvm-mirror/clang/blob/master/include/clang-c/Index.h)), do something to it, and try to save it. Howl will freeze. And stay frozen. For a *long* time...

**Comment by shalabhc** [comment]
I tried this and was not able to reproduce it. Saving was almost instantaneous for me - no freezing.

**Comment by kirbyfan64** [comment]
Aaaaaand....now it works. No clue why...
