### ISSUE TITLE
Weird error frenzy with editor-delete-line at EOF

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#109]
Two ways to reproduce:

Method 1

1. Open a non-existent file with an extension that should be stylized.
2. Run the command `editor-delete-line` (I have this bound to `ctrl_shift_k`, but using `alt_x` works).

The error message is `../lib/aullar/styling.moon:105: GapBuffer#fill(0, 0): Illegal offsets (size 0)`

Method 2 is a bit more interesting;

1. Open a non-existent file with an extension that should be stylized.
2. Enter exactly one newline.
2. Run the command `editor-delete-line`.

The error message is `../lib/aullar/styling.moon:105: GapBuffer#fill(1, 1): Illegal offsets (size 1)`. *However*, if I now press backspace one or more times, this error message will appear:

```
../lib/aullar/buffer.moon:395: Styling: Illegal start_offset: 1
```

After about a second, it will change to this:

```
*error in 'cursor-blink' callback handler: ../lib/aullar/cursor.moon:470: attempt to index local 'cur_line' (a nil value)
```

If I un-focus the Howl window and focus back, this error will appear briefly, followed by returning to the previous one:

```
*error in 'signal focus-in-event' callback handler: ../lib/aullar/cursor.moon:470: attempt to index local 'cur_line' (a nil value)
```

**Comment by nilnor** [comment]
I'm having troubles reproducing using either of the above - nothing happens when I try it. Could you double check with master, and provide the exact file name you're using for the non-existent file (in case it's somehow related to this)?

**Comment by kirbyfan64** [comment]
@nilnor I used a file extension that's highlighted. Try `x.c` or `x.moon`. It won't happen if it's an extension that Howl won't try to highlight.

**Comment by shalabhc** [comment]
Yup - I can reproduce this error too (slightly different process, didn't need a newline).

1. Open '/tmp/nosuchfile.py'  (blank buffer appears)
2. Run 'editor-delete-line' from `alt_x`
3. Unexpected error displayed:`../lib/aullar/styling.moon:105: GapBuffer#fill(0, 0): Illegal offsets (size 1)`

Could not reproduce with /tmp/nosuchfile.

Did not investigate further.

**Comment by kirbyfan64** [comment]
@shalabhc Well, if you put the newline, run `editor-delete-line`, and then hit backspace, *then* you see the rest of the errors.

**Comment by nilnor** [comment]
Sorry, my bad - it seems I was hammering `editor-delete-to-end-of-line` instead, I see it now.
