### ISSUE TITLE
howl-lua-eval show an useless horizontal scrollbar under linux

### ISSUE THREAD

**Issue by xcombelle** [howl-editor/howl#121]
with the debian unstable, i3 window manager, executing `howl-lua-eval` shows an useless  scrollbar which disappear when doing scrolling with mouse

![screen shot](https://cloud.githubusercontent.com/assets/69212/10693182/ff8b55be-7996-11e5-861e-81c13b8aa04c.png)

**Comment by kirbyfan64** [comment]
Marking this as bug, since I don't think this is desired behavior!

**Comment by nilnor** [comment]
@xcombelle should be fixed now, but please have a look if you can to verify that it works for you as well.

**Comment by xcombelle** [comment]
perfect !
