### ISSUE TITLE
Open multiple files in buffers, not views

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#123]
Right now, if you do:

```
$ howl file1 file2 file3
```

Howl will open the files in different views. I almost immediately follow that with a few `ctrl_w`s to close all the views except the last. Views are handy, but they're useless past 2 files (the editing area then becomes too thin). If someone wants to open a new view, it's simple enough.

Thoughs?

**Comment by nilnor** [comment]
Done!
