### ISSUE TITLE
Issues related to PR #114 (Faster)

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#130]
I was able to reproduce it! Do the following:

1. Open a new file named `x`.
2. Enter the following text:

    ```
    abc
    def
    ```
3. Select from the beginning of the `c` in `abc` to the end of `def`.
4. Press `i`.

This should cause an error to appear:

```
callbacks: error in 'signal commit' handler: '../lib/howl/buffer_lines.moon:132: attempt to index local 'l' (a nil value)'
```

However, here's the main issue:

1. Open a new file named `x.c`.
2. Enter the following:

    ```c
    if (x) {
        y;
    }
    ```

3. Select from the beginning of the left curly brace `{` to the end of the second line.
4. Press `i`.

The second line will stay there, even though it should have been deleted, but any attempt to do anything with it will cause it to disappear.

**Comment by nilnor** [comment]
Many thanks @kirbyfan64! Both issues was from the same bug, and once reproducible it was a small fix, so I think you pulled off the hard work here by nailing the steps to reproduce it :)

**Comment by kirbyfan64** [comment]
:D
