### ISSUE TITLE
Weird selection issues

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#136]
This makes editing files with long lines (like https://github.com/phase/o/blob/master/o.c) *hell*. Basically, grab the linked file and open. Now scroll to the end of a long line (like https://github.com/phase/o/blob/master/o.c#L139) and try to use the mouse to select from the end to the beginning of the line. Half the the time, the selection will go haywire. It's *hard*. Is there a solution?

**Comment by nilnor** [comment]
While doing stuff with the mouse will probably always be cumbersome, what you encountered was a bug. Try it out in master, it should hopefully work like expected now.

**Comment by kirbyfan64** [comment]
@nilnor It works now.
