### ISSUE TITLE
Better support for embedded languages

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#138]
Case in point: open up an HTML file, put:

```
function() {
```

and hit enter after the '{'. It won't indent like the JavaScript mode does.

**Comment by kirbyfan64** [comment]
I think I know how to implement this. However, is there a way to access the styled buffer from within a style callback (like `Cmt`)?

**Comment by kirbyfan64** [comment]
Would it be possible to have a "currently being styled buffer" global assigned to in `aullar.buffer.refresh_styling_at`?

**Comment by nilnor** [comment]
Having sub modes work better not only in terms of lexing but in functionality would be great, and is something I've also wished for (my personal beefs are indentation and the comment commands). It's not going to happen by mucking around with things at lexing time though, and there will never be a global set  during `refresh_styling_at` on my watch :P

The way forward there would be to capture the sub lexing language identifier (already provided by lexers) and actually store that in an easily accessible manner from the styling. The commands could then dynamically switch between the right modes. I expect it to be a tricky business though.

**Comment by kirbyfan64** [comment]
@nilnor Is it possible to pass user data through lpeg patterns, though? That was the thing I couldn't figure out. Without that, it seemed impossible to figure out what mode to use when its name is captured (like in Markdown).

**Comment by nilnor** [comment]
If you use match  time patterns you're dropped directly into Lua, so yes. The sub lexing pattern commands actually end emitting special styling instructions for sub lexing, which includes a mode identifier (forward engineering for this particular purpose). See for instance the lpeg lexer spec [here](https://github.com/howl-editor/howl/blob/master/spec/aux/lpeg_lexer_spec.moon#L300) for more info. This info is currently ignored however, but the way forward as I see it would be store this, with a efficient and nice way of retrieving it for a particular offset, and dynamically switch  the mode dispatching dynamically to use this for commands.

**Comment by kirbyfan64** [comment]
@nilnor So this is my idea so far:

It's impossible for embedded modes to overlap. Therefore, I think the best way to represent this would to use a sorted array table. Each entry in the table would be another table in the format `{mode: name_of_mode, begin: beginning_offset_of_embedded_lexer, end: end_offset_of_embedded_lexer}`.

Whenever a mode is requested for a specific position `p` in the source file, the first element `e` of the table where `e.begin > p` is found. Then, it would iterate backwards through the table until it finds the first element `e` where `e.begin < p and e.end > p`. (If it reaches a point where `e.end < p`, then it returns, since that means the current offset isn't inside an embedded style). Now it has the mode in `e.mode`.

**Comment by kirbyfan64** [comment]
This has been done for a while now in #173...
