### ISSUE TITLE
Errors with nested styles

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#145]
Just try creating a Markdown file with the following:

    ```lua
    ffi.cdef [[
    
    ]]
    ```

and then type in between the brackets.

**Comment by kirbyfan64** [comment]
Still doesn't work. Create a Markdown file containing:

    ```lua
    ffi.cdef [[{}
    ]]
    ```

Then put the cursor after the first `{` and hit backspace.

![howl_sub](https://cloud.githubusercontent.com/assets/1690697/12212348/dfd52536-b62e-11e5-9943-5f94e47d11cf.png)

**Comment by nilnor** [comment]
Ok, so this should be fixed now, but I'll leave it open until you have had a chance to try something else wrong :)

**Comment by kirbyfan64** [comment]
Looks good!
