### ISSUE TITLE
Shift+Tab doesn't delete spaces after non-whitespace

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#152]
1. Create a new buffer containing 'abcdef'
2. Position cursor after 'c' and press `tab` - this inserts spaces
3. Press `shift_tab` - this moves the cursor back, doesn't delete anything

Expected: the spaces just inserted should be deleted by `shift_tab`.

**Comment by nilnor** [comment]
This is per design - `shift_tab` (or Editor#smart_tab_back really) is only destructive when in the leading indentation, when it un-indents. When not it will move back one indentation column. This has always been the case FWIW. From my limited checking, other editors that I've checked does not do this either, so I don't see a real case for changing this either, but feel free to attempt to convince me :)

**Comment by shalabhc** [comment]
Closing for now since I don't have a strong opinion on this and can't remember the specific case where this would have been useful.
