### ISSUE TITLE
Undo is too greedy

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#156]
Basically:
1. Open Howl.
2. Enter some text.
3. Paste something.
4. Hit `ctrl_z`.

Both the entered AND pasted text will be removed, but only the pasted text should be.

**Comment by shalabhc** [comment]
Seconded.

Additionally, sometimes undo will undo too slowly. E.g. after Howl auto indents a new line on `enter`, invoking undo first undoes the indent, and the next undo removes the newline. I would expect this to be one step for the undo (it was one keystroke for me).

**Comment by nilnor** [comment]
Just for the record the second issue was addressed by 2a217bd.

**Comment by ozra** [comment]
Ah, now I can remove one of the issues on the list I've built up. Reacted to the exact same thing, edit, paste - different snap-points. Ideally every char entered is an event in it self (this can easily be optimized like a common special case, storage wise, when there's a long string of chars entered in linear sequence. Or rather - only the undo-func needs to be changed to pop one char of at a time of every snap-segment that has been entered manually (a paste is of course one unit).
