### ISSUE TITLE
Auto Indenting in Makefiles uses spaces

### ISSUE THREAD

**Issue by its-suun** [howl-editor/howl#169]
```makefile
something:
    gcc hello.c # Here a tab is inserted
    echo "hi" # Here are 4 spaces inserted
```

**Comment by nilnor** [comment]
This is with the 0.3 release, it works in master. We could do a 0.3.1 release, but would using the master branch work for you? We're getting close to 0.4 now, and I can recommend the master branch anyway as it contains a lot of good stuff :)
