### ISSUE TITLE
JS lexer is a bit over-eager with regard to regexes

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#192]
For instance:

```
1 / 2 / 3
```

`/ 2 /` is highlighted as a regex. Neither the CoffeeScript nor Ruby lexers have this problem.

**Comment by nilnor** [comment]
I tightened up the lexing regex requirements. I'm not sure whether this will actually cover all cases, or whether it will cause other problems with valid regexes not being recognized so feedback welcome.
