### ISSUE TITLE
Small secondary font size on Elementary OS

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#206]
Look at the following screenshots

![screenshot from 2016-06-01 20 04 55](https://cloud.githubusercontent.com/assets/1690697/15730698/6ac65af8-2834-11e6-9050-1314ddf1f5a8.png)

![howl_tiny](https://cloud.githubusercontent.com/assets/1690697/15730718/912ce270-2834-11e6-83ac-576d12541730.jpg)

The second one makes the differing font sizes more obvious.

(For the curious, yes, I just replaced my Ubuntu install with Elementary. I blame @finnbar. ;)

**Comment by finnbar** [comment]
@kirbyfan64 Ha, nice, I wasn't trying to persuade you to switch to Elementary but it seems like I did. :)

**Comment by finnbar** [comment]
@kirbyfan64 Also, not to go too off topic, but how did you get that dark toolbar for Howl? Is that a system-wide setting or just messing with some CSS? It looks great!

**Comment by kirbyfan64** [comment]
@finnbar I installed [Elementary Tweaks](https://launchpad.net/elementary-tweaks) and went to Appearance -> Prefer Dark Theme.

**Comment by finnbar** [comment]
@kirbyfan64 Nice! I didn't like the Dark Theme overall, so I changed the .desktop to execute ``env GTK_THEME=elementary:dark howl`` and now it's got its own dark themed toolbar to go with my modified Monokai theme.

![screenshot from 2016-06-02 18 23 26](https://cloud.githubusercontent.com/assets/4217801/15754335/ac1a53fe-28ef-11e6-9d38-e2027149c921.png)
yesssss

**Comment by nilnor** [comment]
@finnbar nice, looks like you got a Monokai/Steinom hybrid theme going on there :)

**Comment by finnbar** [comment]
@nilnor Yeah, loved the background of Steinom so shamelessly stole it. :)

**Comment by rokf** [comment]
@finnbar Mind sharing the theme? Looks nice :lollipop:

**Comment by finnbar** [comment]
[monom.tar.gz](https://github.com/howl-editor/howl/files/297617/monom.tar.gz)

Here's what I've got at the moment! Called Monom because it's a combination of Monokai and Steinom. To use, just extract the archive in your .howl folder and add the following lines to your init.lua:

``
howl.ui.theme.register('Monom', user_file('monom/monom.moon'))
``
``
howl.config.theme = 'Monom'
``
