### ISSUE TITLE
Subreddit

### ISSUE THREAD

**Issue by rokf** [howl-editor/howl#207]
How about a **subreddit**? Would be great for the community. People could post bundles they're working on. Something like `/r/howlio` or `/r/howl_editor`.

`/r/howl` is taken already.

**Comment by kirbyfan64** [comment]
Yeah, that sounds pretty awesome. I think `/r/howl_editor` would work pretty well.

It could also be a place for random questions to avoid cluttering the issue tracker.

**Comment by shalabhc** [comment]
How about howleditor to match the twitter handle?

**Comment by kirbyfan64** [comment]
:+1:

**Comment by shalabhc** [comment]
I jumped the gun: https://www.reddit.com/r/howleditor

I've added the dev team as moderators too.

**Comment by kirbyfan64** [comment]
@shalabhc Yay!! :fireworks: Maybe there should be some sort of "intro post" or something like most other subreddits have. I can do one if @howl-editor/developers is OK with it.

**Comment by shalabhc** [comment]
Go for it!

**Comment by kirbyfan64** [comment]
@shalabhc I also uploading the Howl logo as the image on the subreddit. 

This can probably be closed now!
