### ISSUE TITLE
Errors in init.moon should not cancel startup

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#208]
Following up on the discussion in #205 here.

Currently having an incorrect theme in your init.moon (such as below) will prevent Howl from starting up:

```
config.theme = 'No such theme'
```

Instead, any error during init.moon should just cancel further processing of init.moon and load Howl, displaying the error itself prominently.

Perhaps it should also open init.moon and scroll to the location where the error was encountered?

**Comment by kirbyfan64** [comment]
I totally agree. To go a bit further, syntax errors should also not prevent Howl from opening. One of the most annoying things about when I started learning MoonScript was when I'd put some kind of wrong syntax in `init.moon`. I'd then have to open up gedit to fix the file.
