### ISSUE TITLE
Misaligned highlights with line-padding

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#209]
Highlights are misaligned, producing a ghost or offset effect. Here is a shot with `config.line_padding = 5`. The effect gets worse with increasingly larger values of line_padding.

![misasligned-highlights](https://cloud.githubusercontent.com/assets/7066873/15788246/66e76e2a-297b-11e6-8e0e-7069e7ee6f47.png)

I have empirically determined that this was introduced in 93760428d.

**Comment by nilnor** [comment]
Fixed now, so have a look.

**Comment by shalabhc** [comment]
Yes, it's fixed!
