### ISSUE TITLE
How can I control window 'gap' size?

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#214]
Hello,

after some initial troubles with init.moon (no easy to look at example, I suggest adding one into share/examples) I got this thing run, somewhat customized to my liking.

I would however like to maximize window space "usage". 

For now I added simple theme into my repo, with which I could tweak 'view' panel borders to size 1. However I have trouble figuring out how to control 'gap' between 'view' panels. Preferably I would like to set it to 1 or 0 pixels wide. I am using solid color background so I don't mind I won't see background 'picture'.

\<edit>
Thinking about it a bit more, it would be cool if I could get rid of 'command entry' gap on the bottom as well (eg. to have panel there, only when 'command entry' is active, as it's panel would pop into place). Gap is too small, to *not to 'pop' bigger* when alt-x is pressed, and once that happens and when 'command entry' activates, it will make space for itself automatically, thus I consider bottom gap pretty useless. If it could be set to 0 height through init file it would be awesome as well.
\</edit>

Is this doable?

**Comment by nilnor** [comment]
Given that you have your custom theme in place already, you can control the window spacing with the `inner_padding` and `outer_padding` setting in the `window:` section in your theme. E.g.:

```moonscript
  window:
    outer_padding: 0
    inner_padding: 0 
```

(In the future we'll add a simpler way of just overriding certain theme values which will remove the need for a custom theme for what it's worth).

It's not possible to remove the space used for the command line completely however. That area is used both for the command line and for status messages and the smarts for hiding and showing these intelligently enough so that it would collapse are not there.

**Comment by etosan** [comment]
Thanks! Theme workaround works very well! I am very happy with it!

By the way this editor is great "GUI" wise!

I realized, I completely missed a fact, that there are status message displayed in that panel as well. 

So question one is : Would there be a force of will to add those smarts for hiding and showing status messages **eventually** ?

Question two, slightly related to gaps themselves : Do you plan to **eventually** support 'view' panel resizing ?

**Comment by nilnor** [comment]
The answer to both of these questions are the same in a sense I think, in that it will take someone willing to put in the work to do it. And at least for me personally, there are a lot of other things that are higher up on the prio list. The latter at least is something that has been discussed previously, but so far it hasn't been that big of an issue. That could change of course, say if some other feature is added that would depend on having a smaller view.

Regarding the status, I'll just know that we have noticed previously that it can also become jarring with to much size changes, i.e. it becomes disturbing. I don't know whether this would be the case here, but I just though I'd mention it.
