### ISSUE TITLE
Update syntax highlighting on new save

### ISSUE THREAD

**Issue by finnbar** [howl-editor/howl#220]
Feature request: update the syntax highlighting on save.
When you save a file (and give it a file extension), the file stays with its original syntax highlighting and must be manually closed and reopened to update this. This is particularly annoying when you open a new buffer (so have no syntax highlighting) and save it as "file.lua" or similar.

**Comment by shalabhc** [comment]
:+1: I think what should happen is that the buffer mode should get updated when you 'save-as'.

BTW, instead of reopening the file, you can use the `buffer-mode` command as a workaround.

**Comment by finnbar** [comment]
That sounds good! That's a useful workaround, thanks. :)

**Comment by nilnor** [comment]
I can fix this, it's not a giant change. However, that also makes this a good candidate for someone wishing to try out some Howl development (work to be done is fixing according to @shalabhc's comment, and add a spec verifying it). So I'll leave this for a few days in case someone else wants to do it :)

**Comment by shalabhc** [comment]
Should this go in `buffer.save_as`, `buffer._associate_with_file` or the `save-as` handler? Note that adding it to the buffer module would introduce a new dependency (`buffer -> mode`) that doesn't currently exist.

**Comment by nilnor** [comment]
The current mode setting for a buffer is currently outside of the buffer itself, so considering that I think the best place right now would be to place the logic in the `save-as` command.

**Comment by shalabhc** [comment]
Does that sill need a spec given the current 'save-as' command doesn't have any?

**Comment by nilnor** [comment]
It seems simple enough that I wouldn't say it's strictly necessary, but it would be nice to have. In general it makes sense to start adding specs for the more advanced commands.
