### ISSUE TITLE
Rust mode

### ISSUE THREAD

**Issue by vegai** [howl-editor/howl#224]
Howdy,

I started working on a Rust mode. I based it on bundles/c, added keywords and primitive types, and removed some things that are obviously not in Rust. I didn't find any documentation of howl bundles, so I basically don't have any clue what I'm doing :) It does a half-decent job in its current phase, however, much nicer to look at than monotone gray everywhere.

The branch is here: https://github.com/vegai/howl/tree/rust/ 

Any pointers to documentation that could help me finish this? If anyone else wants to do the last 20%, that's fine too.

Here's a non-exhaustive list of what's missing:
  
- numbers are colored everywhere, but they should be colored only if there are no chars before them
- consts are ALL_CAPS, perhaps they could be lexed
- if it's possible to hook into external programs when saving, running rustfmt/clippy/cargo check might be nice features
- "self" could be lexed
- use statements
- tags #[...]
- impl blocks and structs
- CamelCaps things are by convention struct types, so they could be lexed

**Comment by kirbyfan64** [comment]
> - numbers are colored everywhere, but they should be colored only if there are no chars before them

See https://github.com/howl-editor/howl/blob/master/bundles/python/python_lexer.moon and, in particular, the `-B'.'`.

`B` means "preceded by" and `-` negates, so you could do something like:

```
number = c 'number', -B(alpha) * any {
```

> - consts are ALL_CAPS, perhaps they could be lexed

See the C lexer:

https://github.com/howl-editor/howl/blob/master/bundles/c/c_lexer.moon#L95

> - if it's possible to hook into external programs when saving, running rustfmt/clippy/cargo check might be nice features

Check out the Go bundle:

https://github.com/howl-editor/howl/blob/master/bundles/go/go_mode.moon#L32

> - "self" could be lexed

You could do:

```
self = c 'special', word { 'self' }
```

> - use statements
> - tags #[...]
> - impl blocks and structs

For tags, I *think* something like this would work:

```
tag = c 'preproc', P'#[' * scan_to ']'
```

Not sure exactly what you mean by "use statements" and "impl blocks and structs"; could you give an example?

> - CamelCaps things are by convention struct types, so they could be lexed

The JS lexer does this:

https://github.com/howl-editor/howl/blob/master/bundles/javascript/javascript_lexer.moon#L40

Hope this answers your questions!

**Comment by shalabhc** [comment]
Really excited to see this going! Looks like @kirbyfan64 addressed most of your issues. I just have some general tips based on my experience:

* While there are no docs for Howl bundles, lexing itself is via LPeg which has decent docs here: http://www.inf.puc-rio.br/~roberto/lpeg/. 

* Howl adds some util functions and constants on top of LPeg, which you can see in the other lexers.

* PEGs (and LPeg) have a 'first matching rule wins' policy, so when a rule matches, subsequent rules are not even checked. Eg. if the final grammar has a rule (e.g. `a+`) before another narrower one (e.g. `a+b+`) then the latter will never match as the first one will always match and consume the `a+` part.

* Work in small increments, from one working grammar to another.

* Create a `misc/examples.rust` in your bundle - this is required for merge anyway and helps test the lexer during development.

* Bind a keystroke to the `bundle-reload-current` command - invoke this after you edit and save any bundle file and it will reload that bundle. The *current* bundle is determined based on the open buffers. This may be specially useful in conjunction with `misc/examples.rust`.

OK, that's all I can think of for now.

**Comment by abaez** [comment]
Great work so far! I have a rust lexer I was planning to migrate to howl from Textadept. It could help your voyage, considering the lpeg lexer definition is practically identical. You can see a link below to the lexer:

https://github.com/abaez/ta-rust/blob/master/rust.lua

**Comment by nilnor** [comment]
I also want to point out that for for cargo check, etc., there's work currently in progress for adding a generic inspection framework - this would be a perfect fit for jacking in these tools once it's done.

**Comment by abaez** [comment]
Thanks to @vegai bringing this issue up.

I went ahead and did a simple migration of my current work on the Textadept's rust module into a howl bundle. It has the lexer working the same as in Textadept and eventually will have all the features that made it so well received on Textadept, but on howl. 

https://github.com/abaez/howl-rust

**Comment by vegai** [comment]
I fixed most of the things @kirbyfan64 suggested now. No external program hooks yet, though.

@abaez looks like this is much more complete than what I've hacked together from C. Do you mind if I adapt most/all of it here?

**Comment by abaez** [comment]
@vegai go for it! I'll be expanding the bundle in iterations on my migration repo. Eventually it'll merge with your work and get one nice happy bundle of rust to rule them all.

**Comment by nilnor** [comment]
@abaez @vegai and when that happens, please open a PR so that we can get it into the Howl core :)

**Comment by abaez** [comment]
Going with reference of what @shalabhc stated on [gitter], I would like to know what procedure to take with the bundle going forward. The [howl-rust][1] bundle is already functional and usable. And I'm going to keep working on it. Yet, don't know if @nilnor wants the bundle also integrated into howl. 

I really do want to continuously expand the state of the bundle to be feature equivalent to the [one I wrote for textadept][2], but don't know if it's alright to spam up the changelog with the changes I tend to do on these things...  

[gitter]: https://gitter.im/howl-editor/howl?at=57b916675ffbca3e3cfc19bb

[1]: https://github.com/abaez/howl-rust
[2]: https://github.com/abaez/ta-rust

**Comment by vegai** [comment]
Thank you. I had far less time to spare for this one than I assumed, unfortunately

**Comment by abaez** [comment]
@vegai no problem! Had a similar situation as well these last few months.

**Comment by abaez** [comment]
Closing due to #257 merged in.
