### ISSUE TITLE
Uni bindings not working as intended?

### ISSUE THREAD

**Issue by hvze** [howl-editor/howl#226]
I have been reading up on the issues about the alt key on osx and apparently there was a whole discussion and fix, however command+a and any other keybinds that require the alt key don't work at all.

**Comment by kirbyfan64** [comment]
I thought Alt was bound to Option, not Command? Wasn't Command bound to Ctrl?

**Comment by shalabhc** [comment]
Can you give an example of a specific command you are trying to invoke and they keystroke you are using? `command+a` is not bound to anything from what I see in keymap.moon.

**Comment by hvze** [comment]
Im posotie that Command+A is supposed to select all the text in the window.
Command+C and Command+V work as intended, but things like Command+A and Alt+X (to open command window) do not work at all.

**Comment by kirbyfan64** [comment]
In Howl, selecting everything is Command+**Shift**+A. IIRC Alt+X didn't work for some weird reason, so someone added an alias with the Command key, though I can't recall...

**Comment by hvze** [comment]
Ah okay, Ill see about custom keymaps and figuring out the binds, thanks!

**Comment by shalabhc** [comment]
Take a look at keymap.moon, specifically the osx section. Should be easy to add a mapping if needed. Feel free to submit a pr too.

**Comment by hvze** [comment]
While tinkering with the keymap I found that on my macbook, meta and ctrl behave weirdly, As if they are interchangeable..

**Comment by shalabhc** [comment]
Try the `describe-key` command to see what events and keystroke translations they produce.
