### ISSUE TITLE
Drag select misbehaving for edge cases

### ISSUE THREAD

**Issue by equim** [howl-editor/howl#240]
There are a few related issues regarding mouse selection:

* Drag select to the top of the view selects several lines down.
* Double click then drag doesn't select full words.
* Triple click then drag doesn't select full lines.
* Triple click does not select the line ending, meaning triple click -> delete leaves an empty line.

The first one is a strange bug.  The rest, I believe, do not do what the user expects and are not how most text editors behave.

**Comment by shalabhc** [comment]
Can you elaborate on the first one? I am unable to reproduce (or understand what you mean perhaps).

The others seem like reasonable feature requests. I didn't realize that's how most editors work :) I just checked Emacs and Atom - both do word-wise and line-wise selection as you describe.

**Comment by equim** [comment]
Sorry for being a bit vague, I found it quite hard to describe.

Click and drag very slowly to the top of the editor view and when you get within a few pixels of the top the cursor moves down a line (decreasing the selection range).  Drag another pixel higher and the cursor moves down another line.  This happens for up to 3 lines and then dragging further beyond the top of the view moves the cursor back to the top.

In code, the explanation is that at [lib/aullar/view.moon:796](https://github.com/howl-editor/howl/blob/c253f8cfa97551a51ff0ba2937e5cef79070b5ea/lib/aullar/view.moon#L796) pos is nil but event.y is between 0 and 4 so we end up at the else which moves the cursor down:

```moonscript
    pos = @position_from_coordinates(event.x, event.y)
    if pos
      @cursor\move_to :pos, extend: true
    elseif event.y < 0
      @cursor\up extend: true
    else
      @cursor\down extend: true
```

**Comment by shalabhc** [comment]
Ah, I can reproduce it now!

Not sure how to fix it though :neutral_face:

**Comment by shalabhc** [comment]
Doh! You already have a bugfix PR - great!. I'll let @nilnor review that one :smile:

**Comment by equim** [comment]
Good to know someone else has reproduced it.  Unfortunately my 'fix' for that bug is the worst part of my PR!
