### ISSUE TITLE
Lag with long identifiers and autocomplete

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#243]
Well, this is a weird one. :/

Do the following:

1. Open up a new file. Name does NOT matter.
2. Copy-and-paste the following text:

```
HOWL_TEST_LONG_STRAIGHT_STRING
HOWL_TEST_LONG_STRAIGHT_STRING
```

Now, if, at the end of the last line, you enter some underscores (e.g. `HOWL_TEST_LONG_STRAIGHT_STRING__`), you'll notice some considerable lag.

**Comment by shalabhc** [comment]
Reproducible here. Setting `complete=manual` seems to fix the issue, so it does seem related to completions.
