### ISSUE TITLE
cursor_blink_interval does not apply to command line

### ISSUE THREAD

**Issue by equim** [howl-editor/howl#249]
The cursor_blink_interval config option does not affect howl's command line cursor which always blinks with an interval of 500ms.

**Comment by equim** [comment]
I had a go at trying to fix this but gave up for now as the config system seems to use advanced lua features that I don't yet understand.  The config option is currently registered in lib/howl/ui/editor.moon and that also watches for changes, applying them to all editors.  Perhaps this logic should be moved out of there to cursor.moon to apply to all cursors.

**Comment by shalabhc** [comment]
I think the current system support different blink intervals for different aullar views (each view has its own config), so maybe we just need to replicate the editor.moon logic in TextWidget too. The command line uses TextWidgets to display the editable line itself.

I tried to play with this to see if it would work but ran into an issue. If you execute the following code:

```
howl.app.window.command_line.command_widget.view.config.cursor_blink_interval = 100
```

It first makes the cursor solid (i.e. no blink), but if you defocus the window and refocus it, the new setting takes effect. Don't know why.
