### ISSUE TITLE
Border around window

### ISSUE THREAD

**Issue by Supernerd11** [howl-editor/howl#263]
There is a weird border around the window

![screenshot from 2016-10-03 12-42-01](https://cloud.githubusercontent.com/assets/13929036/19034962/e6718b6c-8966-11e6-8626-237ab2fa178a.png)

**Comment by nilnor** [comment]
This is using the 0.4 release I'm guessing? If so, could you check whether this is working in master? If so (which I suspect it is) I can look at preparing a 0.4.1 release with the relevant fixes.

**Comment by Supernerd11** [comment]
Describe key gives me meta_alt_x. I think it may be a problem with my laptop, as it happens when i set shortcuts too.

**Comment by Supernerd11** [comment]
Fixed the problem. It was wayland changing alt + anything to alt + meta + anything. Switched to X and all worked.

**Comment by kirbyfan64** [comment]
@Supernerd11 I think you mixed your replies between this issue and #262...

**Comment by Supernerd11** [comment]
I did.

**Comment by Supernerd11** [comment]
This was also fixed by switching to X though

**Comment by rokf** [comment]
I'm having a similar issue on the latest **elementary OS**. The border is very small in my case but stands out when using a light color scheme for example. Could this be related?
![border](https://cloud.githubusercontent.com/assets/2836852/21472865/32ccba96-caed-11e6-944b-c10c345f0b3b.png)

**Comment by rokf** [comment]
I don't remember changing anything and I haven't switched to Wayland as far as I know :thinking:.

I've tried fiddling with CSS in `GTK_DEBUG=interactive howl` and changing the box-shadow, margin and border-radius properties. If I remember correctly making border-radius to 0 and something else made it possible to hide the weird outline but I couldn't get the shadow to work so the window looked flat and alien.

**Comment by kirbyfan64** [comment]
@rokf And that was with the latest version from `master`?

Oh, and you're using Loki, right? ...I might have to try this again...

**Comment by rokf** [comment]
`elementary OS 0.4.1 Loki (64-bit)` and `master` branch yup

**Comment by kirbyfan64** [comment]
Huh, looks like the same thing is happening on Windows now too...?

**Comment by nilnor** [comment]
This was fixed in master via 41ae10ae.
