### ISSUE TITLE
howl.Project signals

### ISSUE THREAD

**Issue by Supernerd11** [howl-editor/howl#265]
I would like to have signals for when adding projects. Also, if a open a directory with the howl command: `howl path/to/dir` it should add dir as a project instead of crashing.

**Comment by kirbyfan64** [comment]
> I would like to have signals for when adding projects.

FYI, as a really, *really* ugly workaround, you can do:

```moonscript
orig_project = howl.Project
howl.Project = (...) ->
  proj = orig _project ...
  -- Do stuff with proj here.
  -- ...
  proj
```

> Also, if a open a directory with the howl command: `howl path/to/dir` it should add dir as a project instead of crashing.

I had considered proposing this a while back, but I just assumed that I was probably the only person who wanted it!

Also, you may find this interesting: https://github.com/kirbyfan64/howl-proj

**Comment by nilnor** [comment]
I do think we should do something reasonable when passed a directory argument - I'm not sure exactly what it is though. One simple solution would be to always start off with the `open` command, starting in the specified directory. Or we could that only for unrecognised directories and start with `project-open` for known projects. Votes or other suggestions?

**Comment by Supernerd11** [comment]
I like the second idea, bit would like per project config files. I kind-of imlementet that in my in file. I can ipload it if you wish.

**Comment by nilnor** [comment]
Per project configuration is something that we want as well - it's not trivial to get that working in a reasonable fashion however (e.g. it needs to fit in in a good way with the current buffer -> mode -> global configuration chain. I know @shalabhc looked at previously, but I think that's on the back burner now.

**Comment by shalabhc** [comment]
Yes I had some ideas based on discussion around revamping the config system to include per-project stuff, but nothing more than that unfortunately.

Anyone is free to take it on if they want, of course.

**Comment by Supernerd11** [comment]
I could take it on. I basically made a simple per project config by iterativley looking for a file, moving up a directory, and look again, etc, until it found it. Then it just ran the file. This is the code:
```lua
local function load_project()
    local location = howl.config.project_file_location
    local file_location
    location =  current_buffer().file
    while true do
        if howl.io.File(location.path .. "/howl_project.moon").exists then
            require('moonscript').dofile(location.path .. "/howl_project.moon")
            file_location = howl.io.File(location.path .. "/howl_project.moon")
            break
        elseif howl.io.File(location.path .. "/howl_project.lua").exists then
            dofile(location.path .. "/howl_project.lua")
            file_location = howl.io.File(location.path .. "/howl_project.lua")
            break
        elseif location.path == "/" then
            return false
        else
            location = location.parent
        end
    end

    howl.Project.add_root(location)
end
```

**Comment by Supernerd11** [comment]
Exlusion of a directory in projects would be nice too.

**Comment by shalabhc** [comment]
As a related update, there's now a PR for the config system: #294

**Comment by shalabhc** [comment]
We have a better config system now where you can have per project or per directory config values. I don't think we have project signals, but I'm still going to mark this bug obsolete. If we need signals a bug with more detailed requirements can be filed.
