### ISSUE TITLE
Add a way to disable the editor slider in a theme

### ISSUE THREAD

**Issue by its-suun** [howl-editor/howl#269]
Since `color` and `alpha` don't work for my editor slider, i would like to remove it, but currently there's no way to do that (or i didn't find it).

**Comment by rokf** [comment]
You'd like to hide the scrollbar?  There's a vertical_scrollbar boolean property. The same goes for horizontal. You can do `set vertical_scrollbar=false` in the command window or set it in your `init` file.

**Comment by its-suun** [comment]
Oh.. :S totally forgot to check `set`. Thanks!
