### ISSUE TITLE
bytecode_loader() should not use outdated '.bc' files

### ISSUE THREAD

**Issue by mfxmfx** [howl-editor/howl#291]
The function bytecode_loader() in lib/howl/init.lua should not use oudated .bc files but load the .moon file if it is newer.

Unfortunately I do not know how to do a "stat()" in lua - as a workaround I'm currently using the zsh shell function below in my howl.zsh start wrapper.

```
function remove_outdated_bytecode { (
    local d=$1
    local f bc
    [[ -d $d/bundles ]] || return
    [[ -w $d/bundles ]] || return
    cd $d || exit 1
    find bundles lib -type f '(' -name '*.lua' -o -name '*.moon' ')' -print0 | LC_ALL=C sort -z | while read -r -d $'\0' f
    do
        bc=${f:r}.bc
        if [[ $bc -ot $f ]]; then
            echo "info: removing $bc"
            rm -- $bc
        fi
    done
) }
```

**Comment by nilnor** [comment]
This is actually be design and for a reason - start-up time. Checking for newer source files for all byte code versions is slow and thus makes start-up slower. When developing for Howl the assumption is that you're using Howl for the development, and Howl will automatically update the bytecode for you as you save. If you use another editor you'll have to account for this yourself.

Given the above, this will not change. I'd be open to a PR that adds a command-line flag to enable this kind of behaviour, but it won't be the default.

**Comment by mfxmfx** [comment]
I respect your position (still please be aware that this is quite inconvenient for new contributors), but I don't buy your speed argument - once the files are in the fs cache a stat() is very cheap.

**Comment by nilnor** [comment]
But the files would be in the FS cache only after the startup, no? I did spend time with the startup, measuring times, etc., before, and my impression from that is that it's definitely slower. However, should that prove to not be the case I'll of course reconsider.
