### ISSUE TITLE
Improving default user experience

### ISSUE THREAD

**Issue by mfxmfx** [howl-editor/howl#296]
Hi,

I find some of howl's defaults rather surprising - e.g. removing the selection on editor-copy and binding editor-select-all to ctrl_shift_a instead of ctrl_a.

Before suggesting any (trivial) changes, though, I'd like to get an idea which existing editor you think that the default UI and bindings should be based on, so that I can see if the current behaviour is a bug or feature.

Possible candidates from my personal side would include vim, textadept, geany and sublime text
(atom, qtcreator and vscode might also be worth a look for their default settings).

**Comment by shalabhc** [comment]
Well, vim should be supported via vim mode but the default for Howl is non modal 'always on' editing so another editor could be used as a reference. In fact why restrict to editors only? I think these things should be considered on a case by case basis and we should consider multiple editors as well as other apps.

E.g. even in an edit box in the browser, `ctrl_a` selects all the text and copying does not clear the selection. So in those two cases I'd voice support for any PR to make Howl more conventional.

In general I think we don't always have to follow convention, but there should be a strong reason for going against it.

**Comment by nilnor** [comment]
I agree with everything @shalabhc said. I don't see any one editor being a blueprint for how Howl should function. If there's an established convention/consensus in other editors it makes sense to follow it, unless there's a good reason not to. So, case by case basis it is.
