### ISSUE TITLE
X11 primary selection 

### ISSUE THREAD

**Issue by mfxmfx** [howl-editor/howl#308]
Hi, 

is there a way to enable the X11 primary selection, i.e. pasting with middle mouse button ?

**Comment by nilnor** [comment]
Not ready-made. It would however not be to hard to enable, e.g.:

- Modify `howl.clipboard` to expose access to the primary selection content
- Modify the `_on_button_press` handler in `Editor` to do the right thing

**Comment by kirbyfan64** [comment]
- Use a clipboard manager.

**Comment by mfxmfx** [comment]
Why do think this issue should be closed?

**Comment by nilnor** [comment]
@mfxmfx since it was posed as a question, which was answered. I'm fine with keeping it open as a feature request, which I is what I'm guessing you're after.

**Comment by mfxmfx** [comment]
Thanks!
