### ISSUE TITLE
This and that... (Hurra!)

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#313]
### Praise

First of everything I must say... **FUCKING AWESOME!**

Every few months I look around desperately in hope to find the editor that I _really_ want (been looking for one for 29 years without being fully satisfied, hehe). Sublime drags 1500MB RAM on my machine freshly opened and with just a few files open and with source being closed - no good - no hackability or fixability - though it's otherwise on the right track. Now I've been back to vim the last few months. But then, _this round of checking around_, I found Textadept, but wanted a sleaker text-like ui and found text-redux, and then by curiosity from seeing a Swedish name, I stumbled upon this by pure chance - _it's not like it's easy to find_ - you really should work harder on spreading the word - I'm sure there are millions that will be as happy as I am now, from finding this unpolished diamond!

I'm rambling - that's a compliment, haha.

**Riktigt jävla lovande editor det här!**

### On to something that _resembles_ an issue:

I've so far written down about 80 issues I've come across - most quite small, no show stoppers by far - and many are just subjective matters, though based on what I really think is the most reasonable expectation of function, so: important to RFC at least, I think.

It _is_ highly usable and I've used it exclusively for the last two days since I downloaded it. I haven't coded Lua before, but Moonscript and I clicked immediately. It seems like a _much_ cleaner language than the, otherwise in editors, so pre-dominantly common Python.

So, with that, I'm thinking _I'll wait a few days before posting issues_, because _if_ I get some time off "the daily stuff that must be done" - _I might be able_ to fix a bunch and PR (_fun_) rather than spend the time with writing the issues in (_boring_).

The main gripe now is that I write "wolf" every time instead of "howl", lol. I saw my first wolf in the garden this winter, so when I saw Howl's logo, "wolf" simply got etched in to my brain, haha, have resisted the temptation to symlink it, will only make it harder to work with the API X-).

**Keep up the good work - and don't get a shock if issues is filled to the breadth in a few days!**

_(BTW, you can of course close this "non-issue" as soon as you've read it)_

**Comment by kirbyfan64** [comment]
Oh my god, this is a small world. ;D

**Comment by ozra** [comment]
Haha, we do seem to have the same path in SW! B-) You're always one step ahead X-)

**Comment by nilnor** [comment]
Many thanks for the praise!

Yes, I dare say it could be more publicized, but speaking for myself it's not my particular forte - what time I have I rather spend on development. Everyone is welcome to spread the word though :)

Won't do much about your main gripe I'm afraid, but you could always go with both a symlink and alias the howl module in your `init.moon` :P

Välkommen ombord hur som helst, och hoppas att du trivs med Howl!
