### ISSUE TITLE
Jump-Start Inquiry

### ISSUE THREAD

**Issue by jacroft01** [howl-editor/howl#316]
Hi, I am new to coding and was wondering if anyone would mind offering advice, I would normally just read to answer my questions but I am also a law student and have a job so if anyone can just get my feet off the ground I would appreciate the help.

I am very new to this and apologize if I sound "green":

1) How do I begin an app build for the iPhone? Do I have cry while trying to figure out _how_to_ code from scratch [LOL] or is there a 'template' for me to play with?
2) If so, how do I identify the proper program aka Template?
3) Then what do I do? Are there any simple tutorials available to show me coding for dummies? If I had a resource I could master this in a week or two but have no idea where to start. 
4) Once I get passed the initial "lost" hump, is there somewhere I can research code and the effects on the program?
5) oh yeah, also, is this even the correct 'type' of program to undertake something like building my 'own' custom app? -- i could care less if it ends up bad A and a company makes $$ off it, I just want everything IN ONE PLACE! LOL.

Any guidance or direction is appreciated, thank you kindly for your time!

**Comment by kirbyfan64** [comment]
I think you reported this to the wrong repository...

**Comment by nilnor** [comment]
@jacroft01 As @kirbyfan64 said, this does not seem to be relevant to the Howl editor, but more like generic development questions.
