### ISSUE TITLE
Can't figure out certain details of theming

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#317]
I've made two themes for myself, based on my sublime themes, so it's starting to feel more and more like home. But...

...How the hell do I style an active view differently from the inactive ones'? I've tried figuring it out from the gtk3 docs, but not sure how it translates to the table-structure abstraction in themes? I'll have to excuse myself for not digging up the answer in the howl source - I'm still a bit pressed on time.

**Specifically I'd like to:**
- Change the view-title color (filename) for active view
- Make a highlighted border around the active view (I have 3 - 6 views open at all times - it would be a welcome eye-catcher :) )
- Is it possible to dynamically affect these styles via moon-code? (like flash the bg when activating a view?)

- Also - if anyone know it off the top of the head: can I - "in an official, play nice with bundles, way" - hook in and change how the title and status-line are set? I'd like them both in the same line (used to it from vim, "all in one place", and saves screen estate), instead of two different. And also add an asterisk or whatever to flag if file is modified or not - right now I can only see that in the buffers-list.

**Comment by shalabhc** [comment]
IIRC, theming for active views is not supported yet, but would be very nice to have IMO.

To change the title and status line, play with the following code in your init.moon:
```
howl.ui.editor.register_indicator 'position', 'top_right'
```
To see more indicators, look in [editor.moon](https://github.com/howl-editor/howl/blob/72392c8c94e0e48f890e9ba154ee93cdd6313c75/lib/howl/ui/editor.moon#L872).

**Comment by ozra** [comment]
Alright - thanks for the pointer! I'll make a feature wish issue for "dynamic" styling...

**Comment by ozra** [comment]
Just adding some quick thoughts here before issuing anything anew:

Perhaps code such as that you pointed to should be put in a default "init.moon", when one first starts the editor, not having a "~/.config/howl/init.moon", the editor copies the default init there. The user can then kick off from there at hearts content.

A standard init to start off from also means that default prefs, etc. would (at least initially) follow default namings of variables etc. - _iff_ the user refrains from renaming things and modifying the basic structure too much, the conf would then easily be parsed with moonscript in to an AST so that whenever a user changes a setting via the command line, that could be merged into the "init.moon".
_Or better yet_: the default "init.moon" requires an (initially empty) "auto-confs.moon" at a suitable place in the file, which is also put in the users conf dir. And all command-line confing only mutates that file (to minimize fuckups from mutating the users holy personal conf-file)

Thoughts?

**Comment by kirbyfan64** [comment]
I think the only problem is that Howl has an insane amount of configuration abilities, and having stuff like that in a default `init.moon` would make for a large, intimidating file. Maybe we'd be better off shoving it in the docs somewhere, like a *config file recipes* page or something?

**Comment by ozra** [comment]
Hmm, yes, you're right @kirbyfan64 - definitely could scare peeps away.

In addition to "recipes", perhaps also some examples files along with the install for easy reference.

Yeah, I'll close this fuzzy issue now.
