### ISSUE TITLE
Possibly stupid q: where can I see "in edit console"-ouput when shit goes wrong?

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#320]
Since the Howl-community isn't superbowl sized atm, I hope it's prudent that I ask some questions here in issues - otherwise tell me...

**My workflow atm looks like this** - please hint me as to how I can improve it, if you will.

- Change something in my `init.moon` - perhaps just a short-command
- _(for the following lines, as parenthesis - my short-cuts are of course non-important - `§` is my "leader key")_
- pressing `§`,`r` (that is: `bundle-reload-current`) doesn't seem to work for user-conf??
- So I press `§`,`a`,`e` - that is: "select all" & "evaluate moon code"
   - While not ideal, it makes the updated user-conf take effect
- But...
   - Inevitably, from time to time, shit goes wrong - there's an error in my init.conf
   - **How do I see these errors??** (_I only see a small note in the status bar_)
   - I intuitively looked for `show-console` and similar command (the term I've found to re-occur in 90% of scriptable editors, and of course even browsers, I've used over the years), but found none.
   - It doesn't seem to output on stdout/stderr from Howl either?

**Comment by kirbyfan64** [comment]
#311 would give a traceback when this happens. It's admittedly an annoying issue...

**Comment by ozra** [comment]
Aha! I'll add some thoughts there..
