### ISSUE TITLE
mis-feature: line-padding default value - should be 0!

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#326]
Changing the way fonts are rendered from _their_ default - by default - is generally _not desirable_ to a user.
It took me a while to discover the setting and understand why my preferred fonts made me slightly dizzy even though I changed and changed between them.

Personally the only deviation in this regard _I've ever used_ is "{padding-top: **-1**, padding-bottom: **-1**}" for _specific fonts_, in apps which supports it.

The setting should naturally be 0 by default!

**Comment by nilnor** [comment]
I believe you're in the right here. I'm personally in favour of more space, but it makes sense to keep the default appearance for fonts. Unless someone objects we can change this.

**Comment by shalabhc** [comment]
No objections!
