### ISSUE TITLE
Feature request: FAQ page

### ISSUE THREAD

**Issue by wtok** [howl-editor/howl#339]
I'm a new user, and while trying to configure Howl I've run into a few things I want to do that have no examples for me to work from. Some things are completely undocumented.

For example, I want to adjust some of my Vi-mode keybindings when outside insert mode. The usual `howl.bindings.push {...}` doesn't seem to work. This process (and Vi-mode in general) is completely undocumented. I still haven't figured it out. For that matter, I wouldn't have known that `vi-on` even existed, if I didn't happen to read the "Running commands" section of the configuration guide -- a section title that has nothing to do with Vi. Further, most users will search for `vim` keybindings, not `vi`, so Ctrl+F probably won't help them either.

I think an exhaustive FAQ page with detailed configuration examples, and perhaps an example `init.lua` or `init.moon` file, would go a long way to helping people get set up using Howl. Just add new questions to the page as people ask them, or as you think of them.

I'd be happy to make some question suggestions, although I can't provide many answers.

**Comment by kirbyfan64** [comment]
It would be neat to maybe have a "configuration cookbook" with little interesting `init.moon` snippets.

**Comment by shalabhc** [comment]
I like this cookbook idea - maybe we can get started easily on the wiki?

Also, there's nothing special about `init.moon` (except that it's automatically run) - i.e. the snippets would be valid Howl code, that can be run from anywhere.

**Comment by shalabhc** [comment]
@wtok can you please provide question suggestions here?

**Comment by wtok** [comment]
Sure, I'll put all the questions I've thought of so far. These all pertain to how you do these things in your startup file, i.e. `init.moon` or `init.lua`. I've figured out the answers to some, but not all of these.

- Can I use Vim keybindings?
    - How do I change keybindings for Vim normal and insert modes?
    - How do I disable the cursor going back a space when exiting insert mode?
- How do I change my theme?
- How do I configure tabs and tab width?
- How do I set the options accessible via the `set` command in my init file?
- Can I disable autocompletion within comments?
- Can I add emacs-like hooks to events, e.g., calling a function when saving a file or entering a mode?

**Comment by shalabhc** [comment]
Thanks @wtok - I intend to get this page started on the wiki soonish.

**Comment by ozra** [comment]
@wtok said:
> How do I disable the cursor going back a space when exiting insert mode?

As a 20y+ user of Vim (_as secondary editor_): that's a baaastard!!! - I've spent _so_ many hours (x nights totally!) trying _every_ workaround in space to get that to work reliably in vim, arrrrrgggghhh!

(this was not meant to be a constructive comment - sorry - just _had to release the pressure valve for that since the opportunity came here ;-) )

**Comment by shalabhc** [comment]
Started FAQ here: https://github.com/howl-editor/howl/wiki/Howl-FAQ

Once I think the basics are covered, I'll close this issue.

**Comment by shalabhc** [comment]
BTW, some of the questions are covered fairly well in the manual already - did that not work out for you @wtok? E.g. saving config settings is covered in http://howl.io/doc/manual/configuration.html.

**Comment by wtok** [comment]
Hey, thanks for the FAQ. Looks great so far. One small issue -- the "How do I change my theme?" section says to press `ctrl_x` to get the prompt. That just deletes a line for me, I guess it's meant to say `alt_x`.

As for the saving settings thing, I did find that, but I don't think it clearly explained that `set whatever` directly corresponds to `howl.config.whatever`. It took some experimenting to actually find that connection.

To figure that out, I think I read the "Configuration" section, where it says this:

> [...] to change the current theme interactively you can open up the prompt, and type set theme. [...] See the sections below, Setting variables upon startup and Automatic persistence, for information on how to change a setting so that it persists across restarts.

And then clicked the link to "Setting variables upon startup", and saw this:

```moonscript
-- [...]
-- Set indent globally to two spaces
config.indent = 2
-- [...]
```

And from that I figured out the relationship between `set` and `config`, but only because I had previously used `set indent`, so I guessed at `config.theme`, `config.use_tabs`, etc. and they worked.

I think there really should be a bit that really concretely explains it, something like this:
>To set your theme interactively, type `set theme` into the prompt. **This `theme` setting directly corresponds to the variable `howl.config.theme`, which can be accessed programmatically in your init file. The same applies for every other setting available via the `set` command.**

Which is why I put that question in there -- it could be more clear. 

I think for most users, they're coming from another editor like Emacs or Vim, where they've got a config file setting everything up the way they want it. So when they come to Howl, the first question they ask is "I don't like this. How do I change it in my config file?" and finding the answer to that question is a bit convoluted at the moment.

The FAQ entry for it is a lot better, but I don't think it's quite concrete enough. No-one wants to use the `set` command every single time, so I think explaining how stuff is done in the init file should be the number 1 priority.

**Comment by shalabhc** [comment]
Thanks for the suggestions @wtok ! I've update the FAQ with your suggestions and think you're making very valid points. Lets keep updating the FAQ. In fact, feel free to edit the FAQ directly.

**Comment by shalabhc** [comment]
In spirit of better documentation, there was a good talk at PyCon: https://www.youtube.com/watch?v=azf6yzuJt54

The ideas are expressed here in text: http://divio.com/blog/documentation

Might be useful to organize our documentation around this structure?

**Comment by nilnor** [comment]
We now have a FAQ - can we close this?

**Comment by wtok** [comment]
Sure, FAQ looks good to me, and the community can edit it so I think we're all set here.

I'll close this. Thanks everyone for contributing.
