### ISSUE TITLE
Bug for save-and-quit?

### ISSUE THREAD

**Issue by jlombs** [howl-editor/howl#355]
Can anyone else confirm an issue with save-and-quit not saving open buffers before quitting? It's a rather big issue, so I figured there would be more talk about it if it wasn't likely specific to my machine. 

Howl compiled from source, running Bunsen Labs under Debian 4.9.18. 

Saving works, as does save-as, as does quitting, but the command save-and-quit does not. It's not just an alias problem with wq either. Reproducable by opening any new buffer or existing file, adding text, running the command, and opening the same file up again to find that none of the changes were saved.

**Comment by rokf** [comment]
I have no issues, using `master` branch on `elementary OS`.

**Comment by jlombs** [comment]
I tried pulling it down again, but this time I borrowed an Ubuntu 16.04 machine and tossed it on there, and there were no issues. Same branch, same `init.moon` file, etc as the one giving me trouble. So there must be something not playing right with the backported Bunsen in general (unlikely) or something is fishy with my rig in particular (more likely). 

I'll dig...

**Comment by nilnor** [comment]
@jlombs just to be certain make sure that you haven't ended up with any stale bytecode after local modifications by reissuing `make` in the `src/` directory.

**Comment by jlombs** [comment]
Turned out to be an issue with Aisu somehow disabling all of my `buffer.modified` properties (so in addition to having the `save_all` method fail which was tied into this particular bug, I actually wasn't getting ANY feature that was dependent on having the modified flag be true, eg prompts when quitting before saving a modified buffer, etc).  You'd think this would have caused a bigger issue all along, but I guess that speaks to how surprisingly robust howl is!

Upon removing that bundle manager, everything works as expected. Closing this issue, and opening a new one at [AISU](https://github.com/kirbyfan64/aisu).
