### ISSUE TITLE
Inspection results not shown correctly

### ISSUE THREAD

**Issue by blasti** [howl-editor/howl#369]
Hi,
when I use `ctrl_shift_e` to inspect a lua script, the offending lines in the results buffer get mixed (if there are offending lines).
First line is fine, second is empy, third line is the line which is supposed to be the second line, and so on. I tried latest git.
Attached screenshots:

First line is fine.

![2017-07-12-100842_683x736_scrot](https://user-images.githubusercontent.com/13455612/28108298-4ce897f2-66eb-11e7-9841-96bc02b44951.png)

Second line shows nothing.

![2017-07-12-100859_682x742_scrot](https://user-images.githubusercontent.com/13455612/28108307-52207eb0-66eb-11e7-8098-1b2081d5eb46.png)

Third line shows, what should be in second line.

![2017-07-12-100930_678x740_scrot](https://user-images.githubusercontent.com/13455612/28108317-55f7a482-66eb-11e7-99b5-6dd8ed86ff88.png)

**Comment by shalabhc** [comment]
Which OS are you seeing this on?

**Comment by blasti** [comment]
I'm running Debian GNU/Linux. Emacs tells, that the file uses DOS style CRLF.

**Comment by shalabhc** [comment]
Ah I can reproduce the issue with a file using CRLF. Will work on a fix later.
