### ISSUE TITLE
The scrollbar looks marginally disturbed under KDE Plasma

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#370]
![howl-kde](https://user-images.githubusercontent.com/1690697/28279590-91d91c16-6ae6-11e7-9530-87462b8c717b.png)

**Comment by kirbyfan64** [comment]
Also, this is pretty bad because the cursor will go into the scrollbar, making it impossible to see the last column or two.

**Comment by shalabhc** [comment]
We've had many issues with scrollbars which makes me wonder if it's better to implement our own scrollbar?

**Comment by kirbyfan64** [comment]
Well, this was likely a KDE bug: it's magically fixed now that I upgraded from Kubuntu 16.04 to 17.04.
