### ISSUE TITLE
Weird scrollbar behaviour

### ISSUE THREAD

**Issue by mrshankly** [howl-editor/howl#371]
When using the scroll wheel on my mouse the text scrolls as expected, but the scrollbar doesn't move. If instead I use the arrow keys to navigate everything works as expected.

Clicking and dragging on the scrollbar doesn't work well either, the text moves but the scrollbar doesn't.

I've made a recording of the behaviour: [http://i.imgur.com/jzZmASA.gifv](http://i.imgur.com/jzZmASA.gifv)

Using `git bisect` the first bad commit is 9e9a1209a373aa2794c45bc3fc5421d78500abd3.

### System
I tested on two machines with the same results:
* Linux 4.11.11 on machine 1 and Linux 4.11.9 on machine 2
* GTK+ 3.22.16 on both machines
* The code was compiled with GCC 6.3.0 on machine 1 and GCC 7.1.1 on machine 2

If you need more information or want me to test something else, please do say so. Thanks!

**Comment by kirbyfan64** [comment]
I can actually reproduce this under Kubuntu 17.04, though it seems to have worked on previous versions.

**Comment by kirbyfan64** [comment]
Also, it seems to break under Windows, too.

**Comment by nilnor** [comment]
Thanks a lot for the bisect! In general, Gtk scrollbars are generally a hassle right now, with some issues that are outside of our control (e.g. see [this issue](https://bugzilla.gnome.org/show_bug.cgi?id=765410)). The change pointed at by the bisect was to work around some other scrollbar issue, but perhaps there's some other kind of work-around that can be done. I'm in vacation mode and won't be able to look at it before a few weeks though.

**Comment by nilnor** [comment]
I've revisited the Gtk scrollbar issue and have now added a workaround for the issue. I'll let it simmer in master for a while before closing this issue though to see that it doesn't cause any other problems.
