### ISSUE TITLE
shift_backspace does not do a backspace

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#385]
Would this be a reasonable default for shift_backspace to act as backspace?

**Comment by nilnor** [comment]
I guess, but it also seems like this combination `shift_backspace` could also do something else. Anyway, what's the rationale, typing in all caps using `shift` and you want to delete back while still holding `shift`?

**Comment by italomaia** [comment]
Yeap; most editors do just that. It would be nice if howl did not feel like a "new whole game to learn".

**Comment by nilnor** [comment]
Fair enough, changed in master.
