### ISSUE TITLE
"Cloudflare email protection" in the user guide.

### ISSUE THREAD

**Issue by shviller** [howl-editor/howl#386]
On https://howl.io/doc/manual/configuration.html (as far as I can tell, only this page is affected), there several occurrences such as these:

> The syntax for the `set` command is:
> ```
> set [email protected]_name[layer]=value
> ```

> To set the global value of indent to ‘3’, use the command `set [email protected]=3.`

**Comment by nilnor** [comment]
It seems that Cloudflare's scrape protection thingy started detecting those as emails. I've switched that off now and it looks fine to me, could you check?

**Comment by shviller** [comment]
Yes, looks good from here. Thanks!
