### ISSUE TITLE
Building on OpenBSD Makefile Error

### ISSUE THREAD

**Issue by is73** [howl-editor/howl#388]
Ah: gmake :) consider solved

Trying to build Howl on OpenBSD 6.2 stable

me ~/tmp/howl/src : make
*** Parse error in /home/me/tmp/howl/src: Missing dependency operator (Makefile:25)
*** Parse error: Need an operator in 'endif' (Makefile:27)
*** Parse error: Missing dependency operator (Makefile:28)
*** Parse error: Need an operator in 'endif' (Makefile:30)
*** Parse error: Missing dependency operator (Makefile:31)
*** Parse error: Need an operator in 'else' (Makefile:33)
*** Parse error: Need an operator in 'endif' (Makefile:35)

**Comment by nilnor** [comment]
Good to hear it solved itself, cheers.

**Comment by is73** [comment]
Yes, I apologize :)
