### ISSUE TITLE
 Scrollbar doesn't work properly in 0.5.2 release on OpenBSD 6.2

### ISSUE THREAD

**Issue by peterljung** [howl-editor/howl#390]
I found an issue with 0.5.2 stable release while trying to make a [package](https://github.com/peterljung/howleditor) work for OpenBSD 6.2 (amd64).

First I thought that something was being mixed up by the packaging, but the issue also show on a regular `gmake install`.

* The scrollbar doesn't move while dragging it by the mouse pointer.
* It does move by moving up/down with the keyboard

But it seems to work fine on master on e.g. commit "Update for 0.5.2" (85ca548008cff238a4e0a461a6f00a26d7b6b29d) or latest commit "Tweaks for file backup " (49229c80a7991d5f837a557afe683ce3e36a03be)

**Comment by kirbyfan64** [comment]
I think this is #371, which was fixed in e83e98ee5e9e90286636bb753c85ddd887ba268c.

**Comment by nilnor** [comment]
@kirbyfan64 should be right, this is fixed in master but hasn't been included in the point releases. I've released 0.5.3 now which includes. this.

**Comment by peterljung** [comment]
Thanks! I have updated my OpenBSD package to this release and it seems to work fine now ...

<https://github.com/peterljung/howleditor>
