### ISSUE TITLE
Navigation pane covers up docs at some resolutions

### ISSUE THREAD

**Issue by sharpobject** [howl-editor/howl#391]
At https://howl.io/doc/manual/configuration.html the navigation pane covers up the docs at resolutions around 1700px wide. https://i.imgur.com/BIgyNdM.png

**Comment by nilnor** [comment]
Thanks, I've adjusted things to make it better. The current solution does not really dynamically adjust for header of varying length, but hopefully this will make it acceptable for the time being.
