### ISSUE TITLE
"left" and "right" arrow keys should close the autocomplete box

### ISSUE THREAD

**Issue by imaia** [howl-editor/howl#392]
Imagine you triggered the autocomplete box (mistakenly or not), and you want to not choose the auto-complete right now; actually, you want to move a few characters left, why keep the autocomplete box open if you do that? I believe it should be closed if any key other than "up", "down" and "confirm" (enter, right now), is typed.

**Comment by kirbyfan64** [comment]
Another oddity: type something to open the autocomplete box, then move the cursor somewhere else via mouse and start typing there. The box won't move.

**Comment by shalabhc** [comment]
I agree - pressing `left` or `right` usually means the user doesn't want the autocomplete anymore.

**Comment by nilnor** [comment]
I agree as well FWIW, and I'm sure there are other keys that should cause the complete to close as well (not any key though, as the complete is supposed to stay open and continue to filter as you type).

**Comment by ozra** [comment]
I've reported this earlier, but I might have buried it in a "multi-issue". So; +1 :-)
