### ISSUE TITLE
Shouldn't shift+tab unindent?

### ISSUE THREAD

**Issue by imaia** [howl-editor/howl#393]
TAB indents in most (all?) modern visual editors. Shift+Tab unindents. What if howl could keep this behavior? I believe learn curve should be small, whenever possible.

**Comment by kirbyfan64** [comment]
> Shift indents in most (all?) modern visual editors. 

It does? Do you have an example?

**Comment by imaia** [comment]
I'm sorry. Mistype.

**Comment by stutonk** [comment]
Shift+Tab seems to unindent just fine for me in v0.5.2 for both single lines and multiline selections irrespective of mode.

**Comment by imaia** [comment]
@stutonk if there is no text highlighted, it still unindents?

**Comment by stutonk** [comment]
@imaia Yes, shift+tab unindents for me with no selection so long as the cursor is at the beginning of the text on a line or at the beginning of the line. If it's elsewhere in the line, shift+tab successively moves the cursor backward by the tabwidth until it's in a position that will unindent the line. I've tried it on a few random modes including none, rust, markdown, and lua. In my keymap.moon, shift+tab is set to 'editor-smart-back-tab'. It also seems to work fine for both left and right shift keys. Does shift+tab simply do nothing for you?

**Comment by imaia** [comment]
Actually, the behavior is just as you described. It unindents if in the beginning of the line, moves the cursor there otherwise. If text is highlighted, it unindents normally. I did not know about this "cursor at the beginning of the line" behavior. Now it makes more sense. 

That seems reasonable behavior. I'll close the issue.
