### ISSUE TITLE
Smart indentation

### ISSUE THREAD

**Issue by imaia** [howl-editor/howl#395]
If you have this code:

```
def foo():
    print("hello")
    print("world")  # cursor is in the beginning of this line
```

If you press "enter" to create a new line, indentation will be broken.

**Comment by nilnor** [comment]
Just to clarify, when I do this I end up with correctly indented code, but the cursor is at the wrong column (one less than it should be). Is that what you're seeing as well?

**Comment by nilnor** [comment]
I fixed the erroneous behaviour that I described above in cefc6d0f. I'm closing this under the assumption that this was the problem prompting this ticket - @imaia: please re-open if you meant something else.
