### ISSUE TITLE
Mac OS X 

### ISSUE THREAD

**Issue by Acciaiodigitale** [howl-editor/howl#401]
Hi!

Since I'm using Howl on Linux and now I have to work with an iMac, I successfully compiled Howl to run on Mac OS, but there is problem (icon not showing, key bindings etc)

I see many old conversation about that and I want to know if it is possible to help and which way follow for having a complete port of Howl on Mac OS

**Comment by nilnor** [comment]
Hi there,

as you noticed there have been some work for OSX in the past, with changes going, etc. And there are issues left with it (e.g. as noted in https://github.com/howl-editor/howl/issues/68#issuecomment-160345289). The way I see it what is needed is for someone who using it OSX to contribute patches for any issues - I myself don't use OSX for instance so I can't really help fixing issues I don't see. Generally however, it would be great to get good support for OSX.

**Comment by nilnor** [comment]
With regards to key bindings I'd like to be sure that you're aware that there are special key bindings for OSX? Have a look at the OS X section in [keymap.moon](https://github.com/howl-editor/howl/blob/master/lib/howl/keymap.moon#L126). `meta` is command on OSX.

**Comment by CodelessFuture** [comment]
I now see the keymap (I don't like ctrl_meta_x for 'run')

I want to resolve the icon problem (the Howling Wolf I like very much) and Font Awesome don't display correctly.

**Comment by CodelessFuture** [comment]
Icon resolved!

https://apple.stackexchange.com/questions/256987/creating-an-icon-for-a-homebrew-installed-software-evince-mac-os-x
