### ISSUE TITLE
project-build runs command on global scope instead of file scope

### ISSUE THREAD

**Issue by tuffnerdstuff** [howl-editor/howl#403]
howl version: 0.5.1

I've set a build command for in the config file (`~/-howl/init.moon`) for a certain file scope like this:

`c = howl.config.for_file '/home/stefan/Development/skifoan'`
`c.project_build_command = 'optirun love .'`
`c.indent = 4`

When I check the variable in howl everything looks fine:

![screenshot_20171230_222425](https://user-images.githubusercontent.com/2988903/34457427-4d8bfa36-edb0-11e7-8723-933b1e3ac29e.png)

But when I run the `project-build` or use the hotkey `ctrl_shift_b`, then howl always runs the global command `make` instead of the more specific one `optirun love .`.

**Comment by kirbyfan64** [comment]
Whoops, I think I know what the problem here is...

Fix incoming shortly.

**Comment by kirbyfan64** [comment]
Meanwhile, try changing `lib/howl/commands/app_commands.moon` line 422 from:

```moonscript
    handler: -> launch_cmd get_project_root!, config.project_build_command
```

to:

```moonscript
handler: -> launch_cmd get_project_root!, (app.editor and app.editor.buffer.config or config).project_build_command
```

**Comment by tuffnerdstuff** [comment]
Thanks for the fast response! your suggested patch works for me!
