### ISSUE TITLE
vi mode does not work

### ISSUE THREAD

**Issue by tastyminerals** [howl-editor/howl#406]
I have added the following line to `init.lua` to enable the vi mode following FAQ.
```
howl.signal.connect(`app-ready`, function() { howl.command.vi_on() })
```

It does not work however.

**Comment by nilnor** [comment]
It appears that entry in the FAQ was woefully incorrect in more than one way. I've updated that with correct snippets both for Lua and Moonscript, so have a look again:

https://github.com/howl-editor/howl/wiki/Howl-FAQ#can-i-use-vim-keybindings

You should have seen a error message when starting up though, complaining about errors in the init file?

**Comment by rsolvang** [comment]
Sorry for reviving this old issue, but I can't get Howl to start in vi-on mode. I followed [the instructions](https://howl.io/doc/manual/configuration.html#running-commands) I found in the documentation, but it had no effect. Has something changed again?
