### ISSUE TITLE
Increase default scrolling sensibility

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#415]
Default scrolling for howl views is quite timid. Maybe a higher default would improve usability.

**Comment by kirbyfan64** [comment]
With the mouse? On my system it's pretty fast...what's your OS, Gtk+ version, and desktop environment/window manager?

**Comment by italomaia** [comment]
I'm on xubuntu 17.10; XFCE; GTK 3.22.25; here, it is not fast at all. I can make a video, if needed.

**Comment by nilnor** [comment]
@italomaia I think a video is a good idea. I personally don't scroll using the mouse at all, and before increasing anything there would need to be some consensus that it's desired from more people using it. So far @kirbyfan64 seems to to think the current behaviour is fine, so you need to convince him at least :)

**Comment by kirbyfan64** [comment]
Actually my guess is that this is a platform issue...on my system 500 is borderline broken. I just haven't gotten a chance to look into it yet.

**Comment by italomaia** [comment]
I just made the video. Tonight I'll post it here. VSCode scrolling sensibility is twice howl scrolling sensibility. I can also test with different distros, if needed.

**Comment by italomaia** [comment]
Here you go https://www.youtube.com/edit?o=U&video_id=r13xWjeH7ps

**Comment by shalabhc** [comment]
Edit links don't work except for owner. Fixed link: https://www.youtube.com/watch?v=r13xWjeH7ps

**Comment by italomaia** [comment]
Thanks, @shalabhc My mistake.

**Comment by kirbyfan64** [comment]
Hmm, I have a hunch about what the issue is here... @italomaia What's your font and font size?

**Comment by italomaia** [comment]
Default, for all of them. I can set them all to the same value to test it. Any suggested defaults?

**Comment by italomaia** [comment]
Nice! Do you want me to test it?

**Comment by kirbyfan64** [comment]
Sure!

**Comment by italomaia** [comment]
Just tested. It was a great improvement for usability, in my opinion. I believe the issue is fixed. Thanks.
