### ISSUE TITLE
Hexadecimal literals are not correctly recognised for Rust syntax

### ISSUE THREAD

**Issue by zesterer** [howl-editor/howl#422]
This picture provides an adequate description of the problem.

![image](https://user-images.githubusercontent.com/3268430/37535581-0b8b7d8e-2940-11e8-958c-d259b619ddce.png)

**Comment by shalabhc** [comment]
Hmm, the Rust bundle has no `examples.rs` file :neutral_face: 

Here's a patch that seems to do the right thing, even handles the `u8` etc suffixes: 
```
diff --git a/bundles/rust/rust_lexer.moon b/bundles/rust/rust_lexer.moon
index 8f1fbce2..cd676456 100644
--- a/bundles/rust/rust_lexer.moon
+++ b/bundles/rust/rust_lexer.moon
@@ -26,14 +26,19 @@ howl.util.lpeg_lexer ->
 
 
   -- Numbers.
-  binary = P'0b'^-1 * S'01_'^1
-  number = c 'number', any {
-    binary,
+  hexadecimal =  P'0x' * (any {xdigit, '_'})^1
+  octal = P'0o' * (any {R'07', '_'})^1
+  binary = P'0b' * S'01_'^1
+
+  base_number = c 'number', any {
     hexadecimal,
     octal,
+    binary,
     (digit + '_')^1 -- decimal integer
     float
   }
+  suffix = c 'special', any {'u8', 'i8', 'u16', 'i16', 'u32', 'i32', 'u64', 'i64', 'isize', 'usize'}
+  number = base_number * suffix^-1
 
 
   -- Keywords.

```

I think this could be checked in with an appropriate examples file, if anyone wants to put together a PR.

**Comment by nilnor** [comment]
Yes, here we have a good example of why language bundles always should come with an example file, which slipped in this case. @abaez: I don't suppose you'd want to supplement the bundle with an example file after the fact? :)

Other than that I think it's a good idea to combine the fix with actually adding an example file for the bundle.

**Comment by abaez** [comment]
@nilnor, 

Sure. I'll get to it. Might as well do some spring cleaning and tune up the bundle as well. There's a couple of additions I would like to add to it.

**Comment by nilnor** [comment]
@abaez Many thanks! :pray:

**Comment by shalabhc** [comment]
Looks like it works now.
