### ISSUE TITLE
Glib.h Not found

### ISSUE THREAD

**Issue by Vm900** [howl-editor/howl#425]
Hi
Suprisingly i have libglib2 installed but i keep getting the error glib.h not found
pango package required by gdk-3.0 not found
Perhaps you should add the directory containing 'pango.pc' to the PKG_CONFIG_PATH environment variable.

So i went ahead and installed pango and libgtk3 gets removed automatically.I am at my wits end.
Please help

**Comment by kirbyfan64** [comment]
What distro? Try installing `libglib2.0-dev` to get the header files.

**Comment by kirbyfan64** [comment]
@Vm900 Any updates?
