### ISSUE TITLE
Allow selecting all (ctrl+a) in terminal

### ISSUE THREAD

**Issue by sci4me** [howl-editor/howl#429]
Title kind of says it all. I often find myself wanting to be able to press ctrl+a in the the terminal.

**Comment by shalabhc** [comment]
By 'terminal' I believe you mean the command line? This should be easy enough to add.

**Comment by sci4me** [comment]
That is correct @shalabhc

**Comment by shalabhc** [comment]
@sci4me can you try out https://github.com/howl-editor/howl/tree/command_line_ctrl_a to see if it works?

**Comment by sci4me** [comment]
@shalabhc It works for me

**Comment by shalabhc** [comment]
@nilnor brought up a good point on gitter: should `ctrl_a` move cursor to the start of the text instead?

I think at least some people would expect that to happen, it's the standard shortcut in most shells. What do you think of making `ctrl_shift_a` as the select all shortcut instead?

**Comment by sci4me** [comment]
@shalabhc Doesn't the HOME key bring the cursor to the start of the text?

**Comment by shalabhc** [comment]
OK, this is now merged - `ctrl_a` should select all in the command line.
