### ISSUE TITLE
Feature Request: Add commands to move views.

### ISSUE THREAD

**Issue by mrpandey** [howl-editor/howl#431]
Currently it's not possible to change position of view after creating it. I think there should be commands for moving the current view: `view-move-left`, `view-move-right`, `view-move-up` and `view-move-down`.

**Comment by shalabhc** [comment]
Not sure what you mean by change position of a view? Do you mean resize a view?

**Comment by mrpandey** [comment]
Suppose I just have a single view and now I do `view-new-right-of` to create a new view and open a file in it. Now I want this view to be the left view without closing it and reopening it in a `view-new-left-of`. It would be easier to move it left using `view-move-left`.

`view-move-right`, `view-move-up` and `view-move-down` would be similar.

**Comment by shalabhc** [comment]
All views are equivalent - any view and display any buffer - so swapping the position of two views isn't particularly useful from my perspective. If you are looking at buffer A on the left and buffer B on the right, you can just use 'switch-buffer' to point the right view to buffer A and left view to buffer B. Does that work for you?

**Comment by shalabhc** [comment]
I see. Sounds like you are proposing something similar to i3wm. I'm not opposed to these commands but they would need to be defined a bit more clearly.

In the meantime, can you try the following:

```moonscript
howl.bindings.push
  ctrl_shift_alt_down: -> 
    howl.command.run 'view-close'
    howl.command.run 'view-new-below'
  ctrl_shift_alt_right: -> 
    howl.command.run 'view-close'
    howl.command.run 'view-new-right-of'
```

This might handle your specific case described above. You could similarly add shortcuts for moving a view to other locations.

**Comment by shalabhc** [comment]
(To run the snippet I posted, you can paste it in any buffer, select it and run 'howl-moon-eval'.)

**Comment by shalabhc** [comment]
Did that work @mrpandey ?

**Comment by mrpandey** [comment]
Yup, that seems to work. Thank you very much.

I had to change `ctrl_shift_alt_down` to some other key combination, because in Ubuntu its reserved for switching workspaces.

Sorry, for such a late followup.

**Comment by shalabhc** [comment]
No problem - glad it worked out.
