### ISSUE TITLE
Tab indents wrong number of spaces

### ISSUE THREAD

**Issue by sci4me** [howl-editor/howl#433]
My tab size is set to 4 (spaces) but when I hit the tab key, it indents 2 spaces. I am editing a c file. Version is 0.5.3.

**Comment by shalabhc** [comment]
Can you type `set indent@` in a command line and paste the values you see for different scopes?

**Comment by kirbyfan64** [comment]
IIRC tab size only applies to the actual tab character. By default, the tab key just indents with spaces, the number of which is determined by the indent variable, not tab_size.

**Comment by shalabhc** [comment]
Ah right there's `config.tab_width` vs `config.indent`. You need to set the latter.

**Comment by sci4me** [comment]
Yeah that was the problem; the existence of both is quite confusing, but that fixes it. Thanks!
