### ISSUE TITLE
tilde directories trailing '~'

### ISSUE THREAD

**Issue by s373** [howl-editor/howl#437]
Hi,Howl is great, what I've been looking to use for ages.. 

I've stumbled across an unexpected behavior: Howl interprets trailing '~' in directories, suggesting making new /home/user inside the directory. 

makes sense if you want to quickly go home, but affects all work done in directories~. you can open the right files from a shell by calling $ howl ./dir~/file1.cpp, but then happens again and makes working hard on these dirs, and have to switch to gedit or atom to have work done here.

Keep up the great work

**Comment by shalabhc** [comment]
Ah yes I can reproduce this.

I think the issue is with File.expand_path. Should be able to submit a fix soonish.

**Comment by s373** [comment]
Thanks!

**Comment by s373** [comment]
perfect, works like a charm
