### ISSUE TITLE
save-config doesn't work correctly for fonts

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#444]
Run `set font@global=courier` followed by `save-config`. This saves the font in .howl/system/config.lua but restarting Howl does not update all fonts as seen after running `set font@global=...`. It only updates the title bars.

Setting `howl.config.font = 'courier'` in init.moon works as expected.

Reported by nspthegreat in gitter.

**Comment by nilnor** [comment]
The problem here is that the automatic save functionality doesn't actually trigger any kind of notification for these values, which it must for the configuration values to properly propagate, e.g. in this case to aullar.

@shalabhc something you can have a look at at some point?

**Comment by shalabhc** [comment]
Ah I see - yes I'll look into this.

**Comment by cipriancraciun** [comment]
I don't know if this has been fixed in the development branch, but in v0.6 (the latest released version) it is still present.
