### ISSUE TITLE
VI mode automatically upon startup

### ISSUE THREAD

**Issue by Vm900** [howl-editor/howl#446]
Hi
How do i configure howl to automatically start in vi mode.
The proposed howl.command.vi_on! doesn't work howl complains
Thanks

**Comment by nilnor** [comment]
Thanks for reporting! The documentation was unfortunately out of date. I've updated it now with the correct example:

```moonscript
howl.signal.connect 'app-ready', ->
  howl.command.vi_on!
```

**Comment by Vm900** [comment]
@nilnor Thanks.It works now
