### ISSUE TITLE
command or some infrastructure to show all `key mappings`/`keybinds` (preferably all scopes too)

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#451]
Hello, so I returned back to howl as user, after some hiatus.

I like it so far, but I am fighting hard with moonscript and few things.

I got some rudimentary keybinds working, but I am unable to discover others, or at least get their full list.
Would it be possible to provide some command or something to dump all keybinds somewhere for further inspection? Preferably nested (following scopes (or modes) or how the context thingy is called).

Thank you for consideration.

**Comment by MarcusE1W** [comment]
In the Wiki is a description how to use the command line pretty much like a command palette.
Means all commands are listed with their assigned shortcuts.

https://github.com/howl-editor/howl/wiki/Howl-FAQ#can-i-get-a-comand-palette-similar-to-atom-or-sublime-text

You can also search the command list.
I find that quite helpful to discover shortcuts and commands.

If you just want to try it  press Alt-x for the command line and then TAB in the command line.
You will see the same list that the script above opens. Once you are tired to press TAB you can use the script.

**Comment by etosan** [comment]
thanks will look into it

**Comment by shalabhc** [comment]
Looks resolved.
