### ISSUE TITLE
multiline interaction view is broken

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#452]
It appears that "yes/no" interaction is broken on really long questions and paths.

![broken-multiline-interaction](https://user-images.githubusercontent.com/411502/41662418-9fc5e05c-7490-11e8-8790-cccd46850b1b.png)

It would be cool if interaction knew how to wrap around long question.

**Comment by kirbyfan64** [comment]
The arrow seems to signify that it *is* wrapping...but the wrapped next is below the bottom of the interaction.

**Comment by etosan** [comment]
Indeed, it means interaction is not growing upwards, which might be a problem in cases like these.

**Comment by shalabhc** [comment]
This is fixed in the new branch (command-interaction-refactor).

![howl-cmdline-wrap](https://user-images.githubusercontent.com/7066873/54408852-e7d94b80-46a0-11e9-993f-0ffd01d8b9ab.png)

**Comment by shalabhc** [comment]
Since we're not going to fix in master but just merge the command-interaction-refactor, I'm going to close this.
