### ISSUE TITLE
bug: off by one error in selection engine

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#463]
It seems like there is **off by one** error in `howl`'s selection engine.

When doing selection using <kbd>shift</kbd> + <kbd>arrow keys</kbd> (and their combination with modifiers like <kbd>ctrl</kbd>) character directly under the cursor is included into selection.

When selecting line this way and deleting it, errors like following one happen. Before deletion state was:
![howl-selection-pre-deletion](https://user-images.githubusercontent.com/411502/44155938-22406924-a09e-11e8-8d71-aa9eca56c5a1.png)
After deletion we get this:
![howl-selection-post-deletion](https://user-images.githubusercontent.com/411502/44155950-33e916da-a09e-11e8-923b-4ecf2096efc1.png)

However this seems to be "wrong". 

After some research I am reporting that this behavior is almost universal, instead:
* Character directly under the cursor **should not be included into selection**. Selection ends first character left of the cursor.
* Cursor can usually be positioned one character past the EOL (end-of-line) to allow for full line selections and deletions (including newline)

This behavior is consistent with `leafpad`,`textadept`,`idea` editors, and windows editors I have access to, like `notepad` and `notepad++` and *in-terminal* editors like `nano` or `dex`.

**Comment by nilnor** [comment]
Thank you for the thorough review of the behaviour in other editors. It's not so much an off by one I'd say but more of as result of the origin of the block cursor - the vi mode. In VI the character under the cursor is included in the selection. You're using block cursor without the VI mode presumably?

Looks like the include-cursor behaviour should be scoped down to the VI mode only.

**Comment by etosan** [comment]
Yes, I am using block cursor in normal editing mode. I am one of those weird arrow keys guys, I never learned to type properly.

Maybe I am misinterpreting this but from your reply it seems to me it can be fixed on my side, what am I supposed to configure?

**Comment by nilnor** [comment]
I just pushed a change limiting the "selection includes cursor" behaviour to the VI mode, so if you pull the latest things should hopefully work like you expect it to.
