### ISSUE TITLE
Cursor pointer on home

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#471]
I noticed that the "home" key takes you to the first character in the line, while in most editors, it takes you to the first non-empty character in the line. I find this behavior quite useful. How do you feel about having it in howl?

**Comment by nilnor** [comment]
The behaviour I believe is already there, but it's not mapped to the `home` key by default. Check out the `home_indent` and `home_indent_auto` commands (you can map your own home key to one of these). We could potentially change the default key binding to map to one of these if people agree.

**Comment by italomaia** [comment]
Well, in my daily routine, going to the first character of the line (not the first non-whitespace character) directly is not really helpful unless one wants to copy the entire line (duplicate behavior), which doesn't happen very often. This change might be helpful.

ps: gonna try out your suggestion in the meantime.

**Comment by italomaia** [comment]
```
howl.bindings.push({
  editor = {
    home = 'cursor-home-indent'
  }
})
```

Works like a charm!
