### ISSUE TITLE
Very long startup  time >10 sec

### ISSUE THREAD

**Issue by MarcusE1W** [howl-editor/howl#472]
Hi.
I have a strange effect on one of my systems. (Archlinux, Howl 0.6-dev)
The program starts but it takes very long (~10 sec) to start. Once started it works normal.
This also happens if I start howl with the `--no-profile` option.

It is probably something in my setup because in another very similar system of mine it works.
I appreciate this is difficult to solve, but are there any suggestions how I could narrow down the cause?
Any tests I could run ?

**Comment by nilnor** [comment]
I've had similar issues in the past for non-mainstream desktop environments (e.g. my i3 environment). In those case it didn't have anything to do with Howl in particular (and I suspect that the same holds true for you as well), but was an issue with D-Bus waiting for stuff before finally timing out and proceeding. Have you tried running it from a terminal to see whether you get any warnings or errors logged? Apart from that perhaps check the system logs and see whether you'll see something.

**Comment by MarcusE1W** [comment]
It has nothing to do with howl. I agree.
I had poked around a bit with dbus, but have not found anything.
As it so happens it works now anyway

Healing hands, thanks.
