### ISSUE TITLE
Set syntax highlight to a buffer

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#475]
Let's say I want to copy some snippet in my howl editor and set the highlight to a language of my choosing (HTML as an example) without actually saving the file. Is it possible?

**Comment by kirbyfan64** [comment]
Alt-X -> buffer-mode

**Comment by italomaia** [comment]
Works like a charm! Maybe this should have a first grade documentation, given it is not something many editors offer (at least not in such a clear way) and howl does.
