### ISSUE TITLE
CTRL+ ARROW KEYS don't stop on white spaces

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#479]
Just noticed something odd about howl, if I hold ctrl + arrow key to right, it doesn't stop on the first white space after a non ponctuation character. If I do the same, with arrow key to the left, it does. 

How would you feel about having both behaving the same way? This behavior would feel more familiar to most people as most editors and browsers (you can test with firefox) behave like this.

**Comment by shalabhc** [comment]
I see. Here are the cursor stop points if I understand correctly:
```
# Current behavior (always start of word):
#sample text: hello hello hello
#ctrl-right:  ^     ^     ^
#ctrl-left:   ^     ^     ^

# Desired behavior (end of word going right, start of word going left):
#sample text: hello hello hello
#ctrl-right:      ^     ^     ^
#ctrl-left:   ^     ^     ^
```

I don't have a strong opinion here. I checked VSCode and Firefox and they do have the latter behavior. Any objections to doing this? This would change selection also - when using `ctrl-shift-right` it would not select the trailing whitespace. Probably a good thing?

**Comment by nilnor** [comment]
I'm OK with changing the behaviour - I don't recall exactly what the rationale was for the current behaviour, but most likely I based that on Scintilla's handling.
