### ISSUE TITLE
Home doesn't remove highlight

### ISSUE THREAD

**Issue by italomaia-bk** [howl-editor/howl#481]
If you have some highlighted code in your buffer and you press home, when the cursor is in the first position of the line, highlight will be kept. Same if cursor is in the last position of the line, and you press "end" key. 

Doesn't seem like expected behavior, as if the cursor moves, when you press home or end, highlight is removed. What do you think?

**Comment by nilnor** [comment]
I agree - I tweaked this now so that the selection is removed even for these cases, hopefully we won't see other scenarios where this proves to be a problem.
