### ISSUE TITLE
Text find followed by Esc cancels find

### ISSUE THREAD

**Issue by italomaia-bk** [howl-editor/howl#483]
If I try to find some text, given I do find it, if I press Esc, to close text search, as I found what I wanted and the cursor is in the righ position, viewport is actually moved back to the last cursor position. 

Doesn't feel intuitive. Maybe it should only do that if there is no text highlighted by the text search command.

**Comment by shalabhc** [comment]
This is by design - 'escape' moves back and 'enter' moves to the currently highlighted position.

**Comment by nilnor** [comment]
Yes, as @shalabhc said this works as intended. This provide an easy way of quickly seeing various occurences (e.g. using arrow keys) but then return to the original point, and `enter` is used for when you actually want to go to a certain hit.
