### ISSUE TITLE
0.6 release ticket

### ISSUE THREAD

**Issue by italomaia** [howl-editor/howl#487]
Is there a roadmap for howl 0.5.4? =3

**Comment by nilnor** [comment]
Renamed to "0.6 release ticket" as that's what the next release will be. There are as always things that could be improved, but I think I'm pretty much ready to release 0.6. I would be interested to hear if anyone else has any outstanding issues that could be considered blockers for the release though?

I'd also welcome any feedback on the new navigation and search functionality in particular.

**Comment by kirbyfan64** [comment]
I mean, I'd like at least for *some* of my couple of PRs where I fixed the issues brought up in the review to be approved...

**Comment by nilnor** [comment]
@kirbyfan64 well, that's reasonable, and I'll go through these :) If you remember, it would be great if you could remove the `awaiting-followup` tag when the PR:s are ready again, or just nag me as I tend to miss these things amongst other email.

**Comment by kirbyfan64** [comment]
@nilnor Well I had pinged you but I guess it indeed did get lost :) I'll go through and remove the awaiting-followup labels on the ones that are ready.

**Comment by italomaia** [comment]
@nilnor what should I look for in the new navigation and search? 
Also, how are odds for multi-cursor?

**Comment by nilnor** [comment]
@italomaia I'm looking for feedback in general as well as testing it out to make sure there aren't any bugs preventing it from working as it should.

The odds are for multi-cursors are zero for the 0.6 release - it's not something I've looked at at all and I'm not aware of any other work going on there that would make it into the release.

**Comment by italomaia-bk** [comment]
But what is expected outcome? Should it be faster, does it give a different behavior in certain cenarios?

**Comment by nilnor** [comment]
@italomaia-bk No, the functionality I mentioned (navigation and file search support) didn't exist in the previous release, so what would be like to have is some general testing of the entire functionality.

**Comment by italomaia-bk** [comment]
How do I test project-file-search? How do I create a howl project? What is a howl project? Same concept as in vscode, atom, eclipse, etc?

**Comment by shalabhc** [comment]
@italomaia (if you haven't figured this out yet) a 'howl project' is just a directory. It is automatically determined as the containing git or hg repo root. If you're not in a git/hg repo, howl will ask you for a directory that represents the project. It then remembers which directory is a 'project directory'. So there is no explicit step to create a project, you just run a command that needs a project (e.g. 'project-open', which opens a file in a project) and it prompts you for a project root unless it can guess it. So it's somewhat loose at the moment but works for most cases.

**Comment by shalabhc** [comment]
Since the release is done, I'm closing this issue.
