### ISSUE TITLE
No prompts when saving modified buffer

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#497]
Howl doesn't prompt "Buffer is modified, close anyway? " when closing modified buffers.

**Steps**
1. Open a new buffer
2. Write some text
3. Close buffer (ctrl_w)
Observed: Buffer closes with no prompt.

**Details**
I traced this down to some weirdness with the `.modified` property, but didn't dig deeper. Run this code:

```
b = howl.Buffer!
b\append 'hello'
b._modified, b.modified
```

I expect these to both be `true`, but I see `true, false`.

**Comment by shalabhc** [comment]
OK after a clean install I don't see it - so probably something local messing this up. Closing. Will update if I track it down.

**Comment by shalabhc** [comment]
OK this was a version of aisu lying around in my .howl/bundles. Related to #363. The derived class reused the same property as the Buffer.modifed.

**Comment by kirbyfan64** [comment]
Rip, though I believe I had worked around that in master a while back (I need to find time to work on aisu again).
