### ISSUE TITLE
Configuration directory to follow XDG standards (~/.config/howl/)

### ISSUE THREAD

**Issue by megatux** [howl-editor/howl#507]
Instead of ~/.howl/ why not follow ["the standard"](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)? :
```
$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
```

**Comment by refi64** [comment]
Howl will fall back to ~/.config/howl if ~/.howl doesn't exist (IMO the order should be reversed but that's not a huge deal). That being said, this should probably be in the docs.

**Comment by megatux** [comment]
Oh, I see. I added the issue because the documentation only talked about "./howl"
