### ISSUE TITLE
Font is cut off

### ISSUE THREAD

**Issue by cluelesser** [howl-editor/howl#508]
On a fresh install the font is cut off in the autocomplete box aswell as on the commandline.
![autocomplete](https://user-images.githubusercontent.com/51295898/58764762-77d5b580-856b-11e9-9863-0344f2f8cb0c.png)
![commandline](https://user-images.githubusercontent.com/51295898/58764764-7a380f80-856b-11e9-860e-c13cb6b4149d.png)

I cannot reproduce this on my other machine. Any ideas what could be causing this? Could I offset the issue with some theme related settings?

**Comment by refi64** [comment]
Maybe I'm just blind but I can't really see where this is being cut off? I mean the hinting looks lousy but [Linux font rendering sucks overall anyway](https://pandasauce.org/post/linux-fonts/).

**Comment by cluelesser** [comment]
![autocomplete](https://user-images.githubusercontent.com/51295898/58764861-9b4d3000-856c-11e9-9e19-41084d69e6d4.png)
![commandline](https://user-images.githubusercontent.com/51295898/58764864-9daf8a00-856c-11e9-8573-822cc602b0f9.png)

This should clear things up. Font rendering might not be the best, but this seems to be a bit out of the norm.

**Comment by refi64** [comment]
Ah I see now 🤦‍♂️ Does it scroll if you move the mouse there?

**Comment by cluelesser** [comment]
It's possible to scroll down a little in the autocomplete box and in the commandline entries. I can't make my input visible though. Anything I type in the commandline is only partly visible.

**Comment by nilnor** [comment]
Hmm, that looks weird, it's as if the font extents is reported incorrectly. You could try changing the `font_size` and see if that affects it, but my guess is that will only make the font smaller but still cut off. Do you have global scaling of some kind applied for text that could explain this?

**Comment by cluelesser** [comment]
Changing `font` or `font_size` doesn't work unfortunately. I'm fairly certain I don't use any global scaling or anything similar.

The padding seems to be slightly offset too, could this maybe be the issue?
broken: ![padding_broken](https://user-images.githubusercontent.com/51295898/58800615-9d64cc80-8608-11e9-8ba7-5ec3e5636aa9.png)
normal: ![padding_normal](https://user-images.githubusercontent.com/51295898/58801248-43650680-860a-11e9-8555-ae1c4d7d4128.png)

broken: ![padding2_broken](https://user-images.githubusercontent.com/51295898/58801315-76a79580-860a-11e9-8803-2c1154533093.png)
normal: ![padding2_normal](https://user-images.githubusercontent.com/51295898/58801321-7c9d7680-860a-11e9-9659-1a13f364eabb.png)

Seems like everything would fit perfectly if the padding wasn't so big.

**Comment by cluelesser** [comment]
Did a clean OS install, and everything is aligned properly now. I probably had adjusted some settings.
