### ISSUE TITLE
PLEASE DELETE THIS ISSUE.

### ISSUE THREAD

**Issue by ghost** [howl-editor/howl#511]
This is the error message I got when I ran `make` in the `src` directory on a MacBook Pro. 

`In file included from main.c:4:
./main.h:9:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^~~~~~~~
1 error generated.`

**Comment by refi64** [comment]
You need to install gtk 3 first.

**Comment by scmadhith** [comment]
Installed gtk+3 via homebrew but error message is the same.

`brew list
atk                             libunistring
cairo                           libyaml
fontconfig                      lua
freetype                        lzo
fribidi                         mit-scheme
gdbm                            node
gdk-pixbuf                      opam
gettext                         openssl
glib                            pandoc
graphite2                       pango
gsettings-desktop-schemas       pcre
gtk+3                           perl
harfbuzz                        pixman
hicolor-icon-theme              python
icu4c                           readline
jpeg                            ruby
leiningen                       sbcl
libepoxy                        sqlite
libffi                          vim
libidn2                         wget
libpng                          wine
libtiff                         xz`

**Comment by scmadhith** [comment]
Ok so I thought that would work but it did not. I still get the same error message.
`Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
cc -c main.c -Wall -O2 -g -I/Users/sanjayadhith/Downloads/howl-master/src/deps/LuaJIT-2.1.0-beta3/src  -DHOWL_PREFIX=/usr/local
In file included from main.c:4:
./main.h:9:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^~~~~~~~
1 error generated.
make: *** [main.o] Error 1`

**Comment by shalabhc** [comment]
Lets preserve the title. The issue is closed.
