### ISSUE TITLE
Enhancement: Output of howl-moon-eval in new buffer

### ISSUE THREAD

**Issue by Janfel** [howl-editor/howl#518]
Currently, the output of `howl-lua-eval` and `howl-moon-eval` are displayed as pop-up windows near the cursor. This is fine for small evals, but becomes unwieldy when eval-ing for example `_G`. Furthermore, when eval-ing a global, the output window gets replaced by a warning message, reading: `acessing global - myglobal`.

Therefore I would like the option to have `howl-lua-eval` and `howl-moon-eval` display it's output in a new buffer, instead of the pop-up window. This would also fix not being able to copy the output, as the pop-up window closes when pressing `Ctrl`. (Should this maybe be a separate issue?)

**Comment by shalabhc** [comment]
Note that just evaluating anything automatically copies the result into your clipboard, so this feature is half-done already :smile: 

Opening the result in a new buffer sounds reasonable. Maybe we could have a config variable that defines the number of lines over which the eval functions open a new buffer? Alternatively, since the result is already a buffer (shown by the popup and then thrown away), maybe we can show recent system buffers with a special command?

**Comment by Janfel** [comment]
I didn't know about `eval` copying to the clipboard. This feature should probably be mentioned in the command description, as it changes state outside of the program without noticing the user.

Since writing this issue, I have written a bundle that implements the functionality that I was missing. Here is the [file](https://github.com/howl-editor/howl/files/3775468/init.moon.txt) if anyone is interested.

A config variable might be too fine-grained, but if youre going for Emacs-like configurability then go for it. In my implementation I use a maximum of 200 characters, as this also catches very long strings which only occupy one line.

As for your idea about showing recent system buffers, I think this would be a nice-to-have, but probably not something that will be used very much. But I don't know how prevalent the use of system buffers that might interest the user is in Howl.

**Comment by shalabhc** [comment]
I'm closing this because looks like you were able to make a bundle that provides the behavior you want. The existing behavior in standard Howl seems OK for now.
