### ISSUE TITLE
Config type positive-number not following naming convention

### ISSUE THREAD

**Issue by Janfel** [howl-editor/howl#529]
I noticed that the predefined config type `positive-number` (introduced in e9b418ffa648a53bf8bc9dc48df5994f02c9522f) does not follow the snake case naming convention set by `string_list` (introduced in 3df20f0cd3eea751f8905a337fa2a0700e8921ef). Is there a reason for this and, if not, would you accept a refactor for consistency?

**Comment by Janfel** [comment]
To be clear, this wold be a breaking change, however none of the bundles listed on the wiki page are affected by it and, as this type is not documented, I assume that only few, if any, other bundles use it.

**Comment by nilnor** [comment]
Good catch, and yes, a PR for this would be appreciated. Not really sure what naming convention should be used, but regardless it makes sense to stick to one.

**Comment by Janfel** [comment]
Snake case seems to be the default naming convention for everything but command names, does not require quoting table keys in Moonscript and choosing it would only change [breadcrumbs.moon](https://github.com/howl-editor/howl/blob/master/lib/howl/breadcrumbs.moon). Changing to kebap case would require changing four files and the documented public API. Therefore I don't see any reason to choose kebap case over snake case.
