### ISSUE TITLE
Inconsistent API of command, inspection, mode, etc.

### ISSUE THREAD

**Issue by Janfel** [howl-editor/howl#531]
I have noticed, that the API of modules (?) like `howl.command`, `howl.inspection` and `howl.mode` are rather inconsistent. These are some examples:
- `howl.command` and `howl.inspection` can be indexed, `howl.mode` can't.
- `howl.command.names` is a function, `howl.mode.names` is an auto-generated table, `howl.inspection.names` does not exist at all.
- Registered commands can be aliased, registered modes can not.

To solve this issue, I suggest agreeing on an API convention and imposing it upon these and all similar modules. This is my suggestion for such a convention, with the word "object" refering to the thing being registered:

1. The registered objects are stored in a table indexed by their name.
2. The name is also stored in `someobject.name`. (already the case in all three modules)
3. Aliases are stored in a table separate from the main object table.
4. An alias can either be a string or a table with `tostring()` metamethod.
5. Aliases can not reference other aliases.
6. The module exposes at least the following:
    1. `register(object: table, name: string? = nil)` registers an object, overriding `object.name` with `name` if given
    2. `unregister(object: string or object)` unregisters the named object (don't use aliases)
    3. `alias(target: string or object, name: string, opts: table = {})` creates an entry in the alias table
    4. `unalias(name: string)` removes an entry from the alias table
    5. `by_name(name: string) -> table, bool` returns the named object (use aliases) and if `name` is an alias or not
    6. `names() -> list` returns the list of registered object names plus all aliases that do not point to `nil`
    7. `list() -> list of object` returns the list of registered objects
7. The module can be indexed like this:
    1. `__index(t, k)` calls `by_name(k)`
    2. `__newindex(t, k, v)` calls `register(v, k)` if `v != nil` else calls `unregister(k)`
8. A registered object should always be preferred over an alias to another object.
9. Every function that accepts an object name (excluding `by_name()`), also accepts an object and vice versa.
10. Every function that operates on an object (such as `alias` and `unregister`) is also callable as a method of an object.
11. Modules can choose not to implement aliases, in which case all rules regarding aliases do not apply.
12. If a module chooses to emit a signal or register/unregister (currently only `howl.mode`), the signal contains the registered/unregistered object as parameter of the same name as the module and signal. Example: `howl.abc` would call `signal.emit('abc-registered', {name: myabc.name, abc: myabc})`.

My reasoning:
1. Just the most reasonable thing to do.
2. If acessed through an alias, the real name can be accessed like `howl.x.by_name("alias").name`.
3. No alias can accidentally replace a registered object.
4. I'm not sure about metamethod vs `name` key vs `alias_for` key etc.
5. No alias-cycles.
6. Consistency and backwards-compatibility.
    1. Optional name field for shorter code.
    2. Keeping "dead" aliases around prevents deletion of all aliases when an object is unregistered and reregistered. Also see point 8.
    3. Self explanatory.
    4. Aliases should be removable.
    5. It might be important to know, if the passed name is an alias or not.
    6. Ignoring "dead" aliases.
    7. Compatibility with `howl.inspection` as well as general usefulness.
7. Providing an ergonomic API.
    1. Compatibility with `howl.command` and `howl.inspection` as well as general ergonomicity.
    2. It just feels natural and ergonomic to use Lua's features this way.
8. Imagine a Python-based DSL called Pydsl. When writing Pydsl, basic features can be gained by aliasing Pydsl to Python. If a Pydsl mode is registered, it now overrides the alias, providing advanced features. Accidentally unregistering Pydsl mode twice, should however never unregister Python mode.
9. Preventing inconsistencies and providing an ergonomic API.
10. Providing an ergonomic API, inspired by the config API. Easily implemented using a metatable.
11. Not overcomplicating modules like `howl.interact`.
12. It is currently not possible to access an object using only the name after it has been unregistered.

Please tell me what you think about this.

**Comment by Janfel** [comment]
List of modules that would be affected:
- `howl.interact` (no aliases)
- `howl.inspection` (no aliases)
- `howl.mode`
- `howl.command`
- `howl.config` (no aliases)
- `howl.signal` (no aliases)

If there are some that I didn't notice, I will add them to this list.

**Comment by shalabhc** [comment]
I like this idea. In general I'm a fan of more consistency, makes is easier to remember things and produces fewer surprises. All the suggestions around alias/name precedence and non-cyclic references are great. One issue is this will break a bunch of code. Still, it might be worthwhile to do it now rather than being stuck with it forever.

Here are my comments on some suggestions:

> An alias can either be a string or a table with tostring() metamethod.

Why do we need the latter - any motivating example?

> __newindex(t, k, v) calls register(v, k) if v != nil else calls unregister(k)

Not a fan of this idea. I think registration and unregistration should always be explicit using the provided methods.

> A registered object should always be preferred over an alias to another object.

If names are always strings, the `register` or `alias` call could fail fast if there is a name conflict.

I'm also a bit unsure about mutating passing in objects. These are the following suggestions:
> Every function that operates on an object (such as alias and unregister) is also callable as a method of an object.
> overriding object.name with name if given

The reason is I generally don't expect objects I create to be mutated when passed around. We often do `moon.copy(opts)` for this reason. Say I register the same object twice with different names... the later name will override the first one. Then I might delete the second registration. Extreme example, but I'd prefer to have more immutable objects or at least with fewer points of mutation. Another reason is `object.register` and `object.unregister` might have a different meaning more specific to the object itself (maybe it has a sub registry). So I'd always prefer `register` and `unregister` to be available on the parent container only.

**Comment by Janfel** [comment]
>> An alias can either be a string or a table with tostring() metamethod.
>
> Why do we need the latter - any motivating example?

When creating an alias to a command, the alias can currently be marked as deprecated, by passing the table `{deprecated: true}` as the last parameter to `howl.command.alias`. Thinking about this again, I believe that dropping the latter in favor of a table like this would be preferable:
```
howl.command.deprecated = { foo: true, bar: 'new_bar' }
```
This table would map the names of commands or aliases to `true` or the command/alias they are being deprecated in favor of.

>> __newindex(t, k, v) calls register(v, k) if v != nil else calls unregister(k)
>
> Not a fan of this idea. I think registration and unregistration should always be explicit using the provided methods.

I stand by my reasoning, but you have a point. This would also conflict with the existing `howl.config` API, which I haven't thought of before, making it a no-go. I do believe, that, as this seems natural, any module that does not specify a `__newindex()` metamethod should fail with an error message like "Error: Tried to register the X "Y" by assignment. Use howl.X.register() instead." where X is the module and Y the name of the key being assigned to.

> I'm also a bit unsure about mutating passing in objects.

How about an optional copy parameter? This would allow mutation and metatable trickery, while not having the performance impact that mandating the use of `moon.copy()` would have. Using an object after `register()`ing it without setting `copy` would then be considered a bug on the calling side.
Alternatively, one could:
1. Mandate the use of `moon.copy()` (hurting performance)
2. Mandate not to mutate (severely limiting what can be done with an object)
3. Decide on a case-by-case basis (hurting consistency)

> Another reason is `object.register` and `object.unregister` might have a different meaning more specific to the object itself (maybe it has a sub registry).

This is a fair point that I haven't thought of. A solution would be to put all of these methods under a `self` key, but we would still have the problem that (assuming mode "foo" has not been registered) `howl.mode.foo.self.unregister()` would fail with "Error: Mode foo does not exist" or the even less helpful "Error: nil has no property self" while `howl.mode.unregister("foo")` would succeed with a warning that can be turned off.
This would make calling any of `object.self.*` an antipattern, which is reason enough to drop the idea.

**Comment by shalabhc** [comment]
The separate deprecation table sounds reasonable. Since `register` and `alias` are callable I wonder if `deprecate` should be a function as well.

Regarding storing the name under `name` - that's already the case as you say? If we're saying all `register` methods must accept a table and the table must have a `name` field, then we're already good on that point. I just realized the API proposed in `6i` is `register(object: table, name: string? = nil)` which doesn't match any existing API. I'd rather keep the API the same which is something like `register(name: string, ...)` where `...` are other fields specific to the object being registered (commands have an optional `input` and a `handler`). We can say all tables passed to register *must* have a `name`. Then we don't need to even mutate anything. What do you think? We don't need any copy parameter either.

> I do believe, that, as this seems natural, any module that does not specify a __newindex() metamethod should fail with an error message like "Error: Tried to register the X "Y" by assignment. Use howl.X.register() instead." 

Sounds good +1.

**Comment by Janfel** [comment]
> We can say all tables passed to register *must* have a `name`. Then we don't need to even mutate anything.

Seems like the cleanest solution to me.

**Comment by Janfel** [comment]
> Since `register` and `alias` are callable I wonder if deprecate should be a function as well.

I think marking something as deprecated should only happen on registration. It would make sense to have bundles that alias native commands (i.e. Emacs names), but not bundles that deprecate them.

**Comment by Janfel** [comment]
## Version 2

1. The registered objects are stored in a table indexed by their name.
2. The name is also stored in `someobject.name`.
3. Aliases are stored in a table separate from the main object table.
4. Aliases are strings that contain the `name` of the target object.
5. Aliases can not reference other aliases.
6. The module exposes at least the following:
    1. `register(object: table)` registers an object. The key `name` is mandatory. An existing object is overwritten. If the key `deprecated` is set, add a deprecation.
    2. `unregister(object: string or object)` unregisters the named object (don't use aliases).
    3. `alias(target: string or object, name: string, opts: table = {})` creates an entry in the alias table. If `opts.deprecated` is set, add a deprecation.
    4. `unalias(name: string)` removes an entry from the alias table.
    5. `by_name(name: string) -> table, bool` returns the named object (use aliases) and if `name` is an alias or not.
    6. `names() -> list` returns the list of registered object names plus all aliases that do not point to `nil`.
    7. `list() -> list of object` returns the list of registered objects.
7. The module can be indexed like this:
    1. `__index(t, k)` calls `by_name(k)`.
    2. `__newindex(t, k, v)` calls a module spefic function or `error()` indicating that `register()` should be used.
8. A registered object should always be preferred over an alias to another object.
9. Every function that accepts an object name (excluding `by_name()`), also accepts an object and vice versa.
10. [removed]
11. Modules can choose not to implement aliases, in which case all rules regarding aliases do not apply.
12. If a module chooses to emit a signal or register/unregister (currently only `howl.mode`), the signal contains the registered/unregistered object as parameter of the same name as the module and signal. Example: `howl.abc` would call `signal.emit('abc-registered', {name: myabc.name, abc: myabc})`.
13. Deprecations are stored in a table that maps the name of a command or alias to `true` or the command/alias it is being deprecated in favor of.
14. Modules can choose not to implement deprecations, in which case all rules regarding deprecations do not apply.

My reasoning:
1. Just the most reasonable thing to do.
2. If acessed through an alias, the real name can be accessed like `howl.x.by_name("alias").name`.
3. No alias can accidentally replace a registered object.
4. A simple and elegant solution.
5. No alias-cycles.
6. Consistency and backwards-compatibility.
    1. No need to mutate to insert `name`.
    2. Keeping "dead" aliases around prevents deletion of all aliases when an object is unregistered and reregistered. Also see point 8.
    3. The `opts` argument can contain module-specific keys (i.e. deprecated)
    4. Aliases should be removable.
    5. It might be important to know, if the passed name is an alias or not.
    6. Ignoring "dead" aliases.
    7. Compatibility with `howl.inspection` as well as general usefulness.
7. Providing an ergonomic API.
    1. Compatibility with `howl.command` and `howl.inspection` as well as general ergonomicity.
    2. Objects should be registered explicitly.
8. Imagine a Python-based DSL called Pydsl. When writing Pydsl, basic features can be gained by aliasing Pydsl to Python. If a Pydsl mode is registered, it now overrides the alias, providing advanced features. Accidentally unregistering Pydsl mode twice, should however never unregister Python mode.
9. Preventing inconsistencies and providing an ergonomic API.
10. [removed]
11. Not overcomplicating modules like `howl.interact`.
12. It is currently not possible to access an object using only the name after it has been unregistered.
13. A simple and elegant solution.
14. Not overcomplicating modules like `howl.interact`.

**Comment by shalabhc** [comment]
Looks good to me. One small issue regarding point 9 - `register` will not accept just the string name.

Do you want to implement a PR for this? Can we list all the modules that will be affected?

**Comment by Janfel** [comment]
It seems I forgot to update point 9 when I removed `name` from point 6.i. As this is a small change, I will just edit the comment.

Here is the updated list of modules that expose this kind of functionality.

With aliases:
- lib/howl/command.moon
- lib/howl/mode.moon

Without aliases:
- lib/howl/completion/init.moon
- lib/howl/inspection.moon
- lib/howl/interact.moon
- lib/howl/signal.moon
- lib/ljglibs/callbacks.moon

I'm not listing all modules that have to be looked at, because
```sh
rg '\.register' | rg '^((lib/howl)|(bundles)|(spec))' | wc -l
```
counts 331 calls to `.register` in 94 files.

While I could definitely do all this on a local branch, it would take some time (I'm rather busy currently) and would possibly yield a rather large diff for you to review. How about one PR per module, maybe to a project branch in this repo?

**Comment by shalabhc** [comment]
Doing small PRs seems reasonable. Maybe one PR per module - moves the needle in the right direction even if it doesn't go all the way.

Would be interesting to see if there is some shared library that can be reused for these registries.

**Comment by shalabhc** [comment]
@Janfel are you planning to work on this? If not we could close this for now and put it on some backlog list.

**Comment by Janfel** [comment]
Unfortunately, I am currently bound to other activities, so it would be best we put this on the backlog for now.
