### ISSUE TITLE
Segfault with opening new buffers in non-existent directories

### ISSUE THREAD

**Issue by refi64** [howl-editor/howl#533]
- Open a new file in a new directory, e.g. `xyz/abc`. Modify it in some way to make it unread.
- Without saving the file, open another file in the same, non-existent directory (e.g. `xyz/def`).
- Switch to the first buffer and close it without saving.
- Howl hangs for a moment, then segfaults.

Will look into this soon...

**Comment by shalabhc** [comment]
When you say 'switch to the first buffer' do you mean open the buffer or just close it from the `switch-buffer` list?

**Comment by shalabhc** [comment]
I can't repro - if this is now fixed can we close please @refi64?

**Comment by refi64** [comment]
Indeed it seems to be working now.

**Comment by shalabhc** [comment]
Nice - glad we sorted this out. I think this was also related to some GTK errors being printed in the console which are completely gone now.
