### ISSUE TITLE
Add Ctrl + [ to vi-on option.

### ISSUE THREAD

**Issue by goldendemise** [howl-editor/howl#535]
Per title, currently pressing Ctrl + [ does not exit insert mode as it does in vim. 

The escape key is much less convenient and for me requires leaving home row.

Thank you for the review!

**Comment by ofperfection** [comment]
Attempted to patch this in via https://github.com/howl-editor/howl/pull/536

**Comment by goldendemise** [comment]
My patch only worked for text editing and not language support, and I no longer use the editor
