### ISSUE TITLE
Blog links are broken on page 2

### ISSUE THREAD

**Issue by Delapouite** [howl-editor/howl#539]
Hi

I was skimming through the blog and, starting from the page 2, the links leading to the articles (Read more…) and to the "next page" are broken: https://howl.io/blog/page/2/

example: 
- https://howl.io/2016/05/26/introducing-aullar.html (wrong)
- https://howl.io/blog/2016/05/26/introducing-aullar.html (good)

**Comment by shalabhc** [comment]
Thanks for reporting. I tested a slightly older version (before my recent tweaks e.g. f41adb2be) and it is still broken.

The strange thing is serving from 'middleman' works properly, but doing 'middleman build' creates these broken links. Unfortunately I'm not very comfortable with Ruby or MM but will try to take a look.
