### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Vm900** [howl-editor/howl#550]
Hi,
I'm trying to build howl on cygwin and i keep getting the following error message:
$ make && make install
Downloading http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz..
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Wa
rning: Failed to create the file /tmp/howl_download236851582247153.1428: No
Warning: such file or directory
  0 1001k    0  1452    0     0   1452      0  0:11:46 --:--:--  0:11:46 11616
curl: (23) Failed writing body (0 != 1452)
make: *** [Makefile:56: deps/LuaJIT-2.1.0-beta3] Error 1
=======================================================
Help.Thanks

**Comment by refi64** [comment]
Try under MSYS2, it will run into its own issues but I don't foresee Cygwin ever being supported given that MSYS2 has long surpassed it.
