### ISSUE TITLE
Search in directory

### ISSUE THREAD

**Issue by dgaw** [howl-editor/howl#558]
Perhaps I'm missing something but it seems there's no command in Howl to search the contents of a specific directory.

There is `project-file-search` and `project-file-search-list`, which are very useful but often I find myself wanting to narrow down the results to a specific directory within a project.

E.g. Searching for "command" with `project-file-search-list` in the howl project generates a lot of results, including specs and docs. I'm looking for core code so I'd like to narrow down my search to only the "lib" folder. At the moment I use `buffer-grep` within the results buffer but it feels odd and doesn't allow me to switch between the narrowed-down results and an edit buffer.

Is there a way to do this with stock Howl or would it require some custom code?

**Comment by shalabhc** [comment]
Yeah I don't think there's a command to search a specific directory. I usually run `exec` (`ctrl_shift_r`), cd to the directory and then run `ag`. The result buffer lines are linked to the search result - you can press enter with your cursor on a line and it jumps to the buffer.

Still, it seems like having a folder-search command would be useful. Possibly it could reuse parts of the `project-file-search-list` command.

**Comment by dgaw** [comment]
Thanks for the suggestion @shalabhc ! 

`exec`ing ag is already better than what I've been doing. I think I'll put together a `folder-search` command though. 

I wonder if I should make it a separately distributed bundle or perhaps put in `app_commands.moon` and PR it? I feel like it would be useful to a lot of Howl users and should be part of the editor.

What do you think?

**Comment by shalabhc** [comment]
I think this should be a built-in command, similar to the project search commands. Please reuse the underlying code for those commands. I'm happy to review a PR.

**Comment by dgaw** [comment]
Thanks for the offer to review @shalabhc! I've just added a [PR](https://github.com/howl-editor/howl/pull/559) for this.

**Comment by dgaw** [comment]
Done in #559
