### ISSUE TITLE
Unable to override ruby mode extensions

### ISSUE THREAD

**Issue by jza34** [howl-editor/howl#570]
Hi,
I work on Puppet files, which extension is .pp
By default Howl uses Pascal mode for .pp
I would like to force Howl to use Ruby mode instead. But within my config file.
How to do it?
I know how to do it by editing bundles file and add or remove some extension but I am afraid that a package upgrade will destroy my edit...
Thanks

**Comment by dgaw** [comment]
@jza34 Try adding the following to your `init.moon` file:
```
signal.connect 'file-opened', (args) ->
  file = args.buffer.file
  if file.extension and file.extension\umatch(r'(pp)')
    args.buffer.mode = mode.by_name 'ruby'
```

**Comment by jza34** [comment]
Great! Many thanks it works!
But I had to add `howl` to make it working in my personal config file:
```
 howl.signal.connect 'file-opened', (args) ->
   file = args.buffer.file
     if file.extension and file.extension\umatch(r'(pp)')
       args.buffer.mode = howl.mode.by_name 'ruby'
```

Because `signal` and `mode` are not recognized otherwise

**Comment by dgaw** [comment]
I'm glad it worked @jza34!

Yeah, I have `{:mode, :signal} = howl` at the top of my init file so I omitted them.

**Comment by jza34** [comment]
Right I didn't know it. Now I did it and yes it works!
Thanks!
