### ISSUE TITLE
Buffer list can be cluttered by outputs.

### ISSUE THREAD

**Issue by DriNeo** [howl-editor/howl#574]
I made many tests in a program and for every run inside Howl a buffer is created.

![Capture d’écran_2020-06-14_22-41-11](https://user-images.githubusercontent.com/12350741/84893644-d8189600-b09f-11ea-98d8-1ee79a315804.png)

That made my navigation through the buffers worse and worse, if I want to display the "cheat.txt" as instance I have to scroll more and more.
Why not append outputs in a single buffer ?

Thank you for that great open source software.

**Comment by DriNeo** [comment]
Feel free to answer if you think it is not a problem or if the problem is from my workflow.
I would be happy to learn how you work with external tools like make as instance.

**Comment by shalabhc** [comment]
How are you invoking `cc tree.cc`?

**Comment by DriNeo** [comment]
I enter commands in Howl using ctrl-shift-r.

**Comment by shalabhc** [comment]
A common workflow is to just close the buffer soon after you run it, using `ctrl_w`. You can even do this later from the buffer list view.

However I think a task management bundle would be very useful. I'm pasting some code I have that you could just paste in your init.moon:

Note at the bottom you should be able to just `register_task` for your own tasks and run them.

```moonscript

-- task management

_tasks = {}

register_task = (name, cmd, working_directory) ->
  _tasks[name] = {
    defn: {cmd: cmd, working_directory: working_directory},
    buffers: {}
  }

launch_task = (task_name) ->
  task = _tasks[task_name]
  error "task #{task_name} not found" unless task

  shell = howl.sys.env.SHELL or '/bin/sh'
  p = howl.io.Process {
    cmd: task.defn.cmd,
    working_directory: task.defn.working_directory,
    :shell,
    read_stdout: true,
    read_stderr: true,
  }
  howl.breadcrumbs.drop!
  buffer = howl.ui.ProcessBuffer p
  table.insert task.buffers, buffer

  editor = howl.app\add_buffer buffer
  editor.cursor\eof!
  buffer\pump!

cleanup_task_buffers = (task_name) ->
  task = _tasks[task_name]
  error "task #{task_name} not found" unless task

  remaining = {}
  for buf in *task.buffers
    if buf.process.exited
      howl.app\close_buffer buf
    else
      table.insert remaining, buf
  task.buffers = remaining

select_task = ->
  -- returns a task name
  task_name = howl.interact.select
      items: [k for k, _ in pairs _tasks]
  task_name

howl.command.register
  name: 'run-task'
  description: 'Run a task registered with register_task'
  input: (opts) -> select_task!
  handler: (task_name) ->
    cleanup_task_buffers task_name
    launch_task task_name

-- done task management

register_task 'build-my-project', 'ls', '/tmp'

howl.bindings.push
  ctrl_u: -> howl.command.run_task 'build-my-project'


```
