### ISSUE TITLE
Impossible to see if a buffer is saved at the first glance (unlike most editors).

### ISSUE THREAD

**Issue by DriNeo** [howl-editor/howl#589]
The only way I know is to do ctrl-B and look at the buffer icon in the list.
Many editors put an asterisk close to the buffer name if this buffer contains unsaved text. If you think an asterisk is confusing you can just highlight the buffer name to fix this, I just need a very little visual hint.

**Comment by shalabhc** [comment]
Hi @DriNeo - I've implemented this in the core now with pull request #596. Let me know what you think if you try it out.

**Comment by DriNeo** [comment]
That works fine and solves the limitations of my bundle. Thank you !

**Comment by shalabhc** [comment]
Merged #596
