### ISSUE TITLE
How to turn of autocompletions?

### ISSUE THREAD

**Issue by etosan** [howl-editor/howl#591]
Hello, I localized completer code but I cannot for the love of god come up with a way to disable the "auto" part. I am at the point I would like to have autocomplete disabled for certain buffer types - like for example `.txt` files. Side note: I still want to be able to press and keybind and it should complete as now, which seems should work as is as long as I keep the command bindings.

**Comment by shalabhc** [comment]
You should be able to turn it off by running the command `set complete@global[mode:default]=manual`.

![image](https://user-images.githubusercontent.com/7066873/142806152-e38fe03c-8a8f-4ab4-b0cd-9c09bafe36bb.png)

After that you can run `save-config` to make it permanent. Note this will only apply to mode=default which is for files that don't have a specific mode (such as python or css, etc.). You can turn of auto complete globally by just picking the global option for the above command (will show up as it auto-completes the command itself). Note you can turn it off globally and then set it to `auto` for the modes where you want it to automatically popup.

**Comment by etosan** [comment]
Thank you this did the trick!
