### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by ShalokShalom** [howl-editor/howl#612]
The popular [alternativeto.net](https://alternativeto.net/software/howl/about/) does list Howl as discontinued.

Considering there are at least significant changes since the last releases, could a new one bring this editor more into the focus of attention again. 

To find more people contributing to it. 

Thanks a lot

**Comment by nilnor** [comment]
Yes, not much has been happening for a long time I'm afraid - I personally don't have much time. However, I still use it daily. The next step would be to port it to Gtk 4. I've started this and done much of the groundwork, but it's not yet at a usable stage, and honestly on and off depending on time and inspiration. Whenever I get it there I'll see about a releasing an alpha.

**Comment by ShalokShalom** [comment]
Any release at any point would be better than the current 2019 release, don't you think?
