### ISSUE TITLE
Indentation issue with aullar

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#74]
I open a file `x.c` and start entering some text. It looks like this:

![howl_aullar_indent_1](https://cloud.githubusercontent.com/assets/1690697/9564744/cf6d6b44-4e74-11e5-9a74-f308f3c8728f.png)

Looks fine...wait, why is the indentation bar appearing? The indentation level is obviously set to 4:

![howl_aullar_indent_2](https://cloud.githubusercontent.com/assets/1690697/9564746/df1b5a24-4e74-11e5-9671-0f3a40980382.png)

But if I set the indent to 4 *again*, then it looks normal:

![howl_aullar_3](https://cloud.githubusercontent.com/assets/1690697/9564750/ed4cab7a-4e74-11e5-8bc6-38aef533e3ba.png)

**Comment by nilnor** [comment]
Thanks, some settings was not propagated to aullar properly.
