### ISSUE TITLE
Odd line resizing with aullar

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#75]
I have a feeling I'm going to get kicked out of the howl-editor organization if I keep on opening aullar-related issues. :)

Basically:

1. Open up Howl with a Python file.
2. Start typing `class `. The line will look normal.
3. Now start typing some letters. The line will suddenly become taller. Maybe this is intentional, but to me it looks weird.

**Comment by shalabhc** [comment]
Quite the contrary, I'd say. I, for one, welcome any and all bug reports (specially if they're directed at @nilnor  :stuck_out_tongue_winking_eye: )

This specific instance seems intentional because the class name itself has a taller sized font and Aullar supports mixing lines with different heights (which is an awesome feature IMO). The line height resets once it has a character of a different height. I can't think of a different behavior that would be better.

**Comment by shalabhc** [comment]
Hmm, perhaps there could be a `config.fixed_line_height` variable that forces all styles to use the same line height?

**Comment by kirbyfan64** [comment]
Or make the character heights the same?

**Comment by shalabhc** [comment]
That's up to the theme, I believe. See https://github.com/howl-editor/howl/blob/aullar/bundles/solarized-themes/light.moon#L215

**Comment by nilnor** [comment]
Everything @shalabhc said. I'm guessing you might not have the Purisa font installed, as the purpose of this is made clearer with that as an example:

![var-height-howl](https://cloud.githubusercontent.com/assets/263135/9569131/fd30c584-4f60-11e5-9f96-012b8cfa56ec.png)

As @shalabhc pointed out these things are controlled by the theme, but I'm open for an option that allows anyone to instantly drop back to a droll, enterprise-like appearance. But note that you can't really only limit the font size as different fonts will have different pixel extents for the same given font size. So something like `config.edtior_uniform_font` then which would force both the font and the size. Would that be interesting?

And no, you won't be kicked out :)  On the contrary, all issues found are very much appreciated!

**Comment by kirbyfan64** [comment]
@nilnor But it still looks weird (or maybe it's just the night theme?):

![howl_aullar_line1](https://cloud.githubusercontent.com/assets/1690697/9569227/a0dec87a-4f2a-11e5-8dbd-bfddcde6735e.png)
![howl_aullar_line2](https://cloud.githubusercontent.com/assets/1690697/9569228/a2dabb52-4f2a-11e5-97c4-2334e7c261c0.png)

The line literally *grows*...

**Comment by shalabhc** [comment]
Yes the line grows, but I don't find it weird - perhaps that is subjective?

I think this is kind of like when you type markdown in any editor that understands it and formats on the fly.  The editor knows how to format this line and adjusts the color, font and even height accordingly.

**Comment by nilnor** [comment]
@kirbyfan64 of course the line grows, how could it be otherwise? If one wants variable height fonts then that's the consequence, and if not then an option to force a uniform font and size can be introduced.

**Comment by kirbyfan64** [comment]
Well, I guess. I just thought it looked kind if weird. Nevermind.
