### ISSUE TITLE
Auto-indent doesn't always end on the correct line with curly_mode

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#78]
I'm not quite sure if this is an issue with the `curly_mode` bundle or an issue in the handling of code blocks. Basically, try entering this:

```c
if (1) {
} else if (1) {
```

After you enter the second left curly brace, hit Enter. Instead of auto-indenting, it just goes to the next line.

I'm guessing this might be a bug in the code block handling because of this line in `modes/basic_modes.moon`:

```moonscript
{ '{%s*$', '^%s*}', '}'}
```

and this in `editing/formatting.moon`:

```moonscript
if prev_line\umatch(block_end_p) and ends_previous_block(prev_line, block_start_p)
        return false
```

I'm pretty sure this causes the example to not auto-indent.

**Comment by nilnor** [comment]
I made the block completion a little more robust, which should fix this case, so please try it out.
