### ISSUE TITLE
UTF-8 bugs

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#79]
This is kind of weird...

1. Go [here](http://kirbyfan64.github.io/rs/index.html?script=%24%24x%3D%28%3F%3C!%5C%5C%29%28%28%5C*%7C_%29%7B2%7D%29%0A%5Ct%2F%C2%A0%0A%24x%5C1%2F%0A%24x%28%5CS%28%5C%5C%5C2%7C.%29*%3F%29%3F%5C1%2F%28%5Cn%29%5E%5E%28%28%5E%5E%5C3%29%29%5C3%0A%5C%5C%28%5C*%7C_%29%2F%5Ct%0A%5B%5E%5Ct%5Cn%5D%2F%0A%5Cn%2F_%0A%5Ct_%3F%2F%0A%28_*%29%2F%28%5E%5E%5C1%29&input=The%20**quick%20brown%20fox%20jumps%20over%20the%20lazy**%20dog.%0AThe%20**quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog.%0AThe%20__quick**__%20brown%20**fox__%20jumps**%20over__%20the__%20lazy%20**dog.%0AThe%20__quick%5C____%20brown%20fox%20**jumps%20over%5C**%20the**%20lazy%20%5C**dog.%0AThe****quick%20brown%20fox****jumps%20over%20the%20lazy%20dog.).
2. Copy the line with `\t/ `, making sure to include the space at the end. This is a Unicode non-breaking space.
3. Paste it into Howl.
4. Click around the end of the line. This will come up in the terminal:
    
    ```
    (howl:24664): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
    ```

    If you copy the text from within Howl before closing it, this will also appear:
   
    ```
    (howl:24664): Gtk-WARNING **: Error converting from UTF-8 to ASCII: Partial character sequence at end of input
    ```

**Comment by nilnor** [comment]
So, this should be fixed. I could never reproduce the problem with copying though, so re-open with some clear instructions on how to reproduce if it persists.
