### ISSUE TITLE
Issues with scrolling and auto-complete

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#93]
Basically, create some file (I did `x.c`) and start typing a really long line with a bunch of words. Notice that, once the line goes off the edge of the screen, the most recently typed character is always offscreen. The scrollbar always moves 1 keypress late.

Also notice that, when the cursor is (incorrectly) one past the edge of the screen as stated above, auto-complete won't appear, and `Ctrl+Space` does nothing. If the cursor is at the very right hand edge, `Ctrl+Space`, still does nothing, and this gets dumped to the terminal:

```
(howl:15959): Gtk-CRITICAL **: gtk_widget_set_size_request: assertion 'width >= -1' failed

(howl:15959): Gtk-CRITICAL **: gtk_window_resize: assertion 'width > 0' failed
```

<s>This is kind of a monolithic issue. Sorry. :D</s>

**Comment by nilnor** [comment]
@kirbyfan64 Can you separate this into different issues instead of the monolithic one?

**Comment by kirbyfan64** [comment]
@nilnor The other things were reporting in #97 and #98.

**Comment by nilnor** [comment]
Thanks!

**Comment by nilnor** [comment]
It's likely that this will have to be tweaked further in the future, but have a look at the latest master which addresses this.
