### ISSUE TITLE
Disappearing horizontal scroll bar

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#97]
Open a file with alternating line widths (such as https://github.com/kirbyfan64/o/blob/c/c/o2.c), go to a REALLY long line, and go all the way to the end. Now scroll down via the scroll bar. The horizontal scroll bar will disappear, so now you have to try clicking and dragging to scroll back left. Although the disappearing scroll bar is a cool idea, it doesn't work too well in situations like this.

**Comment by nilnor** [comment]
I added something for this, so have a look and see if you can break it.

**Comment by kirbyfan64** [comment]
Looks great!
